// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.LabServices.Inputs;

namespace Pulumi.AzureNative.LabServices;

public static partial class LabPlanNetworkProfileArgsExtensions
{
    public static global::Pulumi.AzureNative.LabServices.Inputs.LabPlanNetworkProfileArgs WithSubnetId(this global::Pulumi.AzureNative.LabServices.Inputs.LabPlanNetworkProfileArgs @selfRef, global::System.String subnetId)
    {
        @selfRef.SubnetId = subnetId;
        return @selfRef;
    }

}
