// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.ApplicationInsights;

public static partial class ComponentArgsExtensions
{
    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithApplicationType(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ApplicationInsights.ApplicationType> applicationType)
    {
        @selfRef.ApplicationType = applicationType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithDisableIpMasking(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, bool disableIpMasking = true)
    {
        @selfRef.DisableIpMasking = disableIpMasking;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithDisableLocalAuth(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, bool disableLocalAuth = true)
    {
        @selfRef.DisableLocalAuth = disableLocalAuth;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithFlowType(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ApplicationInsights.FlowType> flowType)
    {
        @selfRef.FlowType = flowType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithForceCustomerStorageForProfiler(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, bool forceCustomerStorageForProfiler = true)
    {
        @selfRef.ForceCustomerStorageForProfiler = forceCustomerStorageForProfiler;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithHockeyAppId(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.String hockeyAppId)
    {
        @selfRef.HockeyAppId = hockeyAppId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithImmediatePurgeDataOn30Days(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, bool immediatePurgeDataOn30Days = true)
    {
        @selfRef.ImmediatePurgeDataOn30Days = immediatePurgeDataOn30Days;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithIngestionMode(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ApplicationInsights.IngestionMode> ingestionMode)
    {
        @selfRef.IngestionMode = ingestionMode;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithKind(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.String kind)
    {
        @selfRef.Kind = kind;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithLocation(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithPublicNetworkAccessForIngestion(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ApplicationInsights.PublicNetworkAccessType> publicNetworkAccessForIngestion)
    {
        @selfRef.PublicNetworkAccessForIngestion = publicNetworkAccessForIngestion;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithPublicNetworkAccessForQuery(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ApplicationInsights.PublicNetworkAccessType> publicNetworkAccessForQuery)
    {
        @selfRef.PublicNetworkAccessForQuery = publicNetworkAccessForQuery;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithRequestSource(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ApplicationInsights.RequestSource> requestSource)
    {
        @selfRef.RequestSource = requestSource;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithResourceGroupName(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithResourceName(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.String resourceName)
    {
        @selfRef.ResourceName = resourceName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithRetentionInDays(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.Int32 retentionInDays)
    {
        @selfRef.RetentionInDays = retentionInDays;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithSamplingPercentage(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.Double samplingPercentage)
    {
        @selfRef.SamplingPercentage = samplingPercentage;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithTags(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithTags(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithTags(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs WithWorkspaceResourceId(this global::Pulumi.AzureNative.ApplicationInsights.ComponentArgs @selfRef, global::System.String workspaceResourceId)
    {
        @selfRef.WorkspaceResourceId = workspaceResourceId;
        return @selfRef;
    }

}
