// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.B2bi;

public static partial class PartnershipExtensions
{

    extension(Partnership)
    {
        public static Partnership New(string @id, global::Pulumi.AwsNative.B2bi.PartnershipArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new Partnership(@id, @args, @options);
        }

        public static Partnership New(string @id, global::System.Action<global::Pulumi.AwsNative.B2bi.PartnershipArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AwsNative.B2bi.PartnershipArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new Partnership(@id, @args, @options);
        }

    }

}
