// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.Storage;

public static partial class StorageTaskAssignmentArgsExtensions
{
    public static global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs WithAccountName(this global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs @selfRef, global::System.String accountName)
    {
        @selfRef.AccountName = accountName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs WithProperties(this global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs @selfRef, global::Pulumi.AzureNative.Storage.Inputs.StorageTaskAssignmentPropertiesArgs properties)
    {
        @selfRef.Properties = properties;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs WithProperties(this global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.Storage.Inputs.StorageTaskAssignmentPropertiesArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.Storage.Inputs.StorageTaskAssignmentPropertiesArgs();
        @configure(@item);
        @selfRef.Properties = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs WithResourceGroupName(this global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs WithStorageTaskAssignmentName(this global::Pulumi.AzureNative.Storage.StorageTaskAssignmentArgs @selfRef, global::System.String storageTaskAssignmentName)
    {
        @selfRef.StorageTaskAssignmentName = storageTaskAssignmentName;
        return @selfRef;
    }

}
