// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Deadline.Inputs;

namespace Pulumi.AwsNative.Deadline;

public static partial class FleetServiceManagedEc2InstanceCapabilitiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithAcceleratorCapabilities(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::Pulumi.AwsNative.Deadline.Inputs.FleetAcceleratorCapabilitiesArgs acceleratorCapabilities)
    {
        @selfRef.AcceleratorCapabilities = acceleratorCapabilities;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithAcceleratorCapabilities(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Deadline.Inputs.FleetAcceleratorCapabilitiesArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Deadline.Inputs.FleetAcceleratorCapabilitiesArgs();
        @configure(@item);
        @selfRef.AcceleratorCapabilities = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithAllowedInstanceTypes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Collections.Generic.List<global::System.String> allowedInstanceTypes)
    {
        @selfRef.AllowedInstanceTypes = allowedInstanceTypes;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithAllowedInstanceTypes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.AllowedInstanceTypes = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithAllowedInstanceTypes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.AllowedInstanceTypes = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCpuArchitectureType(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::Pulumi.AwsNative.Deadline.FleetCpuArchitectureType cpuArchitectureType)
    {
        @selfRef.CpuArchitectureType = cpuArchitectureType;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCpuArchitectureType(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Deadline.FleetCpuArchitectureType> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Deadline.FleetCpuArchitectureType>();
        @configure(@item);
        @selfRef.CpuArchitectureType = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCustomAmounts(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Deadline.Inputs.FleetAmountCapabilityArgs> customAmounts)
    {
        @selfRef.CustomAmounts = customAmounts;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCustomAmounts(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Deadline.Inputs.FleetAmountCapabilityArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Deadline.Inputs.FleetAmountCapabilityArgs>();
        @configure(@list);
        @selfRef.CustomAmounts = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCustomAmounts(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Deadline.Inputs.FleetAmountCapabilityArgs>> @create)
    {
        @selfRef.CustomAmounts = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCustomAttributes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Deadline.Inputs.FleetAttributeCapabilityArgs> customAttributes)
    {
        @selfRef.CustomAttributes = customAttributes;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCustomAttributes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Deadline.Inputs.FleetAttributeCapabilityArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Deadline.Inputs.FleetAttributeCapabilityArgs>();
        @configure(@list);
        @selfRef.CustomAttributes = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithCustomAttributes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Deadline.Inputs.FleetAttributeCapabilityArgs>> @create)
    {
        @selfRef.CustomAttributes = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithExcludedInstanceTypes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Collections.Generic.List<global::System.String> excludedInstanceTypes)
    {
        @selfRef.ExcludedInstanceTypes = excludedInstanceTypes;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithExcludedInstanceTypes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.ExcludedInstanceTypes = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithExcludedInstanceTypes(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.ExcludedInstanceTypes = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithMemoryMiB(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::Pulumi.AwsNative.Deadline.Inputs.FleetMemoryMiBRangeArgs memoryMiB)
    {
        @selfRef.MemoryMiB = memoryMiB;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithMemoryMiB(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Deadline.Inputs.FleetMemoryMiBRangeArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Deadline.Inputs.FleetMemoryMiBRangeArgs();
        @configure(@item);
        @selfRef.MemoryMiB = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithOsFamily(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::Pulumi.AwsNative.Deadline.FleetServiceManagedFleetOperatingSystemFamily osFamily)
    {
        @selfRef.OsFamily = osFamily;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithOsFamily(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Deadline.FleetServiceManagedFleetOperatingSystemFamily> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Deadline.FleetServiceManagedFleetOperatingSystemFamily>();
        @configure(@item);
        @selfRef.OsFamily = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithRootEbsVolume(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::Pulumi.AwsNative.Deadline.Inputs.FleetEc2EbsVolumeArgs rootEbsVolume)
    {
        @selfRef.RootEbsVolume = rootEbsVolume;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithRootEbsVolume(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Deadline.Inputs.FleetEc2EbsVolumeArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Deadline.Inputs.FleetEc2EbsVolumeArgs();
        @configure(@item);
        @selfRef.RootEbsVolume = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithVCpuCount(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::Pulumi.AwsNative.Deadline.Inputs.FleetVCpuCountRangeArgs vCpuCount)
    {
        @selfRef.VCpuCount = vCpuCount;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs WithVCpuCount(this global::Pulumi.AwsNative.Deadline.Inputs.FleetServiceManagedEc2InstanceCapabilitiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Deadline.Inputs.FleetVCpuCountRangeArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Deadline.Inputs.FleetVCpuCountRangeArgs();
        @configure(@item);
        @selfRef.VCpuCount = @item;
        return @selfRef;
    }

}
