// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Deadline.Inputs;

namespace Pulumi.AwsNative.Deadline;

public static partial class FleetHostConfigurationArgsExtensions
{
    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetHostConfigurationArgs WithScriptBody(this global::Pulumi.AwsNative.Deadline.Inputs.FleetHostConfigurationArgs @selfRef, global::System.String scriptBody)
    {
        @selfRef.ScriptBody = scriptBody;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Deadline.Inputs.FleetHostConfigurationArgs WithScriptTimeoutSeconds(this global::Pulumi.AwsNative.Deadline.Inputs.FleetHostConfigurationArgs @selfRef, global::System.Int32 scriptTimeoutSeconds)
    {
        @selfRef.ScriptTimeoutSeconds = scriptTimeoutSeconds;
        return @selfRef;
    }

}
