// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.DevCenter;

public static partial class DevCenterArgsExtensions
{
    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithDevCenterName(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.String devCenterName)
    {
        @selfRef.DevCenterName = devCenterName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithDisplayName(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.String displayName)
    {
        @selfRef.DisplayName = displayName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithEncryption(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::Pulumi.AzureNative.DevCenter.Inputs.EncryptionArgs encryption)
    {
        @selfRef.Encryption = encryption;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithEncryption(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DevCenter.Inputs.EncryptionArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DevCenter.Inputs.EncryptionArgs();
        @configure(@item);
        @selfRef.Encryption = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithIdentity(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::Pulumi.AzureNative.DevCenter.Inputs.ManagedServiceIdentityArgs identity)
    {
        @selfRef.Identity = identity;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithIdentity(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DevCenter.Inputs.ManagedServiceIdentityArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DevCenter.Inputs.ManagedServiceIdentityArgs();
        @configure(@item);
        @selfRef.Identity = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithLocation(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithProjectCatalogSettings(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::Pulumi.AzureNative.DevCenter.Inputs.DevCenterProjectCatalogSettingsArgs projectCatalogSettings)
    {
        @selfRef.ProjectCatalogSettings = projectCatalogSettings;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithProjectCatalogSettings(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DevCenter.Inputs.DevCenterProjectCatalogSettingsArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DevCenter.Inputs.DevCenterProjectCatalogSettingsArgs();
        @configure(@item);
        @selfRef.ProjectCatalogSettings = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithResourceGroupName(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithTags(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithTags(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DevCenter.DevCenterArgs WithTags(this global::Pulumi.AzureNative.DevCenter.DevCenterArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
