// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs;

namespace Pulumi.AzureNative.ConnectedVMwarevSphere;

public static partial class OsProfileArgsExtensions
{
    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithAdminPassword(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::System.String adminPassword)
    {
        @selfRef.AdminPassword = adminPassword;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithAdminUsername(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::System.String adminUsername)
    {
        @selfRef.AdminUsername = adminUsername;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithComputerName(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::System.String computerName)
    {
        @selfRef.ComputerName = computerName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithGuestId(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::System.String guestId)
    {
        @selfRef.GuestId = guestId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithLinuxConfiguration(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileLinuxConfigurationArgs linuxConfiguration)
    {
        @selfRef.LinuxConfiguration = linuxConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithLinuxConfiguration(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileLinuxConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileLinuxConfigurationArgs();
        @configure(@item);
        @selfRef.LinuxConfiguration = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithOsType(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ConnectedVMwarevSphere.OsType> osType)
    {
        @selfRef.OsType = osType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithWindowsConfiguration(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileWindowsConfigurationArgs windowsConfiguration)
    {
        @selfRef.WindowsConfiguration = windowsConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs WithWindowsConfiguration(this global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileWindowsConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.ConnectedVMwarevSphere.Inputs.OsProfileWindowsConfigurationArgs();
        @configure(@item);
        @selfRef.WindowsConfiguration = @item;
        return @selfRef;
    }

}
