// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.VideoAnalyzer.Inputs;

namespace Pulumi.AzureNative.VideoAnalyzer;

public static partial class ParameterDeclarationArgsExtensions
{
    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs WithDefault(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs @selfRef, global::System.String @default)
    {
        @selfRef.Default = @default;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs WithDescription(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs WithName(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs WithType(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.ParameterDeclarationArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.VideoAnalyzer.ParameterType> type)
    {
        @selfRef.Type = type;
        return @selfRef;
    }

}
