// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.VideoAnalyzer.Inputs;

namespace Pulumi.AzureNative.VideoAnalyzer;

public static partial class UnsecuredEndpointArgsExtensions
{
    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs WithCredentials(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs @selfRef, global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UsernamePasswordCredentialsArgs credentials)
    {
        @selfRef.Credentials = credentials;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs WithCredentials(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UsernamePasswordCredentialsArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UsernamePasswordCredentialsArgs();
        @configure(@item);
        @selfRef.Credentials = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs WithTunnel(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs @selfRef, global::Pulumi.AzureNative.VideoAnalyzer.Inputs.SecureIotDeviceRemoteTunnelArgs tunnel)
    {
        @selfRef.Tunnel = tunnel;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs WithTunnel(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.VideoAnalyzer.Inputs.SecureIotDeviceRemoteTunnelArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.VideoAnalyzer.Inputs.SecureIotDeviceRemoteTunnelArgs();
        @configure(@item);
        @selfRef.Tunnel = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs WithType(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs @selfRef, global::System.String type)
    {
        @selfRef.Type = type;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs WithUrl(this global::Pulumi.AzureNative.VideoAnalyzer.Inputs.UnsecuredEndpointArgs @selfRef, global::System.String url)
    {
        @selfRef.Url = url;
        return @selfRef;
    }

}
