// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.HealthcareApis.Inputs;

namespace Pulumi.AzureNative.HealthcareApis;

public static partial class ServiceAccessPolicyEntryArgsExtensions
{
    public static global::Pulumi.AzureNative.HealthcareApis.Inputs.ServiceAccessPolicyEntryArgs WithObjectId(this global::Pulumi.AzureNative.HealthcareApis.Inputs.ServiceAccessPolicyEntryArgs @selfRef, global::System.String objectId)
    {
        @selfRef.ObjectId = objectId;
        return @selfRef;
    }

}
