// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Personalize.Inputs;

namespace Pulumi.AwsNative.Personalize;

public static partial class SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithCategoricalHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionCategoricalHyperParameterRangeArgs> categoricalHyperParameterRanges)
    {
        @selfRef.CategoricalHyperParameterRanges = categoricalHyperParameterRanges;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithCategoricalHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionCategoricalHyperParameterRangeArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionCategoricalHyperParameterRangeArgs>();
        @configure(@list);
        @selfRef.CategoricalHyperParameterRanges = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithCategoricalHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Personalize.Inputs.SolutionCategoricalHyperParameterRangeArgs>> @create)
    {
        @selfRef.CategoricalHyperParameterRanges = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithContinuousHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionContinuousHyperParameterRangeArgs> continuousHyperParameterRanges)
    {
        @selfRef.ContinuousHyperParameterRanges = continuousHyperParameterRanges;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithContinuousHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionContinuousHyperParameterRangeArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionContinuousHyperParameterRangeArgs>();
        @configure(@list);
        @selfRef.ContinuousHyperParameterRanges = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithContinuousHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Personalize.Inputs.SolutionContinuousHyperParameterRangeArgs>> @create)
    {
        @selfRef.ContinuousHyperParameterRanges = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithIntegerHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionIntegerHyperParameterRangeArgs> integerHyperParameterRanges)
    {
        @selfRef.IntegerHyperParameterRanges = integerHyperParameterRanges;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithIntegerHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionIntegerHyperParameterRangeArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Personalize.Inputs.SolutionIntegerHyperParameterRangeArgs>();
        @configure(@list);
        @selfRef.IntegerHyperParameterRanges = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs WithIntegerHyperParameterRanges(this global::Pulumi.AwsNative.Personalize.Inputs.SolutionConfigHpoConfigPropertiesAlgorithmHyperParameterRangesPropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Personalize.Inputs.SolutionIntegerHyperParameterRangeArgs>> @create)
    {
        @selfRef.IntegerHyperParameterRanges = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
