// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.ElasticSan.Inputs;

namespace Pulumi.AzureNative.ElasticSan;

public static partial class KeyVaultPropertiesArgsExtensions
{
    public static global::Pulumi.AzureNative.ElasticSan.Inputs.KeyVaultPropertiesArgs WithKeyName(this global::Pulumi.AzureNative.ElasticSan.Inputs.KeyVaultPropertiesArgs @selfRef, global::System.String keyName)
    {
        @selfRef.KeyName = keyName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ElasticSan.Inputs.KeyVaultPropertiesArgs WithKeyVaultUri(this global::Pulumi.AzureNative.ElasticSan.Inputs.KeyVaultPropertiesArgs @selfRef, global::System.String keyVaultUri)
    {
        @selfRef.KeyVaultUri = keyVaultUri;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ElasticSan.Inputs.KeyVaultPropertiesArgs WithKeyVersion(this global::Pulumi.AzureNative.ElasticSan.Inputs.KeyVaultPropertiesArgs @selfRef, global::System.String keyVersion)
    {
        @selfRef.KeyVersion = keyVersion;
        return @selfRef;
    }

}
