// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.CleanRooms.Inputs;

namespace Pulumi.AwsNative.CleanRooms;

public static partial class AnalysisTemplateHashArgsExtensions
{
    public static global::Pulumi.AwsNative.CleanRooms.Inputs.AnalysisTemplateHashArgs WithSha256(this global::Pulumi.AwsNative.CleanRooms.Inputs.AnalysisTemplateHashArgs @selfRef, global::System.String sha256)
    {
        @selfRef.Sha256 = sha256;
        return @selfRef;
    }

}
