// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.MachineLearningServices.Inputs;

namespace Pulumi.AzureNative.MachineLearningServices;

public static partial class CustomForecastHorizonArgsExtensions
{
    public static global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomForecastHorizonArgs WithMode(this global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomForecastHorizonArgs @selfRef, global::System.String mode)
    {
        @selfRef.Mode = mode;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomForecastHorizonArgs WithValue(this global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomForecastHorizonArgs @selfRef, global::System.Int32 value)
    {
        @selfRef.Value = value;
        return @selfRef;
    }

}
