// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.MachineLearningServices.Inputs;

namespace Pulumi.AzureNative.MachineLearningServices;

public static partial class CustomMetricThresholdArgsExtensions
{
    public static global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomMetricThresholdArgs WithMetric(this global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomMetricThresholdArgs @selfRef, global::System.String metric)
    {
        @selfRef.Metric = metric;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomMetricThresholdArgs WithThreshold(this global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomMetricThresholdArgs @selfRef, global::Pulumi.AzureNative.MachineLearningServices.Inputs.MonitoringThresholdArgs threshold)
    {
        @selfRef.Threshold = threshold;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomMetricThresholdArgs WithThreshold(this global::Pulumi.AzureNative.MachineLearningServices.Inputs.CustomMetricThresholdArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.MachineLearningServices.Inputs.MonitoringThresholdArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.MachineLearningServices.Inputs.MonitoringThresholdArgs();
        @configure(@item);
        @selfRef.Threshold = @item;
        return @selfRef;
    }

}
