// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.ContainerService.Inputs;

namespace Pulumi.AzureNative.ContainerService;

public static partial class ManagedClusterPropertiesAutoScalerProfileArgsExtensions
{
    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithBalanceSimilarNodeGroups(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String balanceSimilarNodeGroups)
    {
        @selfRef.BalanceSimilarNodeGroups = balanceSimilarNodeGroups;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithDaemonsetEvictionForEmptyNodes(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, bool daemonsetEvictionForEmptyNodes = true)
    {
        @selfRef.DaemonsetEvictionForEmptyNodes = daemonsetEvictionForEmptyNodes;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithDaemonsetEvictionForOccupiedNodes(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, bool daemonsetEvictionForOccupiedNodes = true)
    {
        @selfRef.DaemonsetEvictionForOccupiedNodes = daemonsetEvictionForOccupiedNodes;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithExpander(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ContainerService.Expander> expander)
    {
        @selfRef.Expander = expander;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithIgnoreDaemonsetsUtilization(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, bool ignoreDaemonsetsUtilization = true)
    {
        @selfRef.IgnoreDaemonsetsUtilization = ignoreDaemonsetsUtilization;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithMaxEmptyBulkDelete(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String maxEmptyBulkDelete)
    {
        @selfRef.MaxEmptyBulkDelete = maxEmptyBulkDelete;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithMaxGracefulTerminationSec(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String maxGracefulTerminationSec)
    {
        @selfRef.MaxGracefulTerminationSec = maxGracefulTerminationSec;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithMaxNodeProvisionTime(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String maxNodeProvisionTime)
    {
        @selfRef.MaxNodeProvisionTime = maxNodeProvisionTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithMaxTotalUnreadyPercentage(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String maxTotalUnreadyPercentage)
    {
        @selfRef.MaxTotalUnreadyPercentage = maxTotalUnreadyPercentage;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithNewPodScaleUpDelay(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String newPodScaleUpDelay)
    {
        @selfRef.NewPodScaleUpDelay = newPodScaleUpDelay;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithOkTotalUnreadyCount(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String okTotalUnreadyCount)
    {
        @selfRef.OkTotalUnreadyCount = okTotalUnreadyCount;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithScaleDownDelayAfterAdd(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String scaleDownDelayAfterAdd)
    {
        @selfRef.ScaleDownDelayAfterAdd = scaleDownDelayAfterAdd;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithScaleDownDelayAfterDelete(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String scaleDownDelayAfterDelete)
    {
        @selfRef.ScaleDownDelayAfterDelete = scaleDownDelayAfterDelete;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithScaleDownDelayAfterFailure(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String scaleDownDelayAfterFailure)
    {
        @selfRef.ScaleDownDelayAfterFailure = scaleDownDelayAfterFailure;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithScaleDownUnneededTime(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String scaleDownUnneededTime)
    {
        @selfRef.ScaleDownUnneededTime = scaleDownUnneededTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithScaleDownUnreadyTime(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String scaleDownUnreadyTime)
    {
        @selfRef.ScaleDownUnreadyTime = scaleDownUnreadyTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithScaleDownUtilizationThreshold(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String scaleDownUtilizationThreshold)
    {
        @selfRef.ScaleDownUtilizationThreshold = scaleDownUtilizationThreshold;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithScanInterval(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String scanInterval)
    {
        @selfRef.ScanInterval = scanInterval;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithSkipNodesWithLocalStorage(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String skipNodesWithLocalStorage)
    {
        @selfRef.SkipNodesWithLocalStorage = skipNodesWithLocalStorage;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs WithSkipNodesWithSystemPods(this global::Pulumi.AzureNative.ContainerService.Inputs.ManagedClusterPropertiesAutoScalerProfileArgs @selfRef, global::System.String skipNodesWithSystemPods)
    {
        @selfRef.SkipNodesWithSystemPods = skipNodesWithSystemPods;
        return @selfRef;
    }

}
