// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.ServiceBus;

public static partial class DisasterRecoveryConfigArgsExtensions
{
    public static global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs WithAlias(this global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs @selfRef, global::System.String alias)
    {
        @selfRef.Alias = alias;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs WithAlternateName(this global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs @selfRef, global::System.String alternateName)
    {
        @selfRef.AlternateName = alternateName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs WithNamespaceName(this global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs @selfRef, global::System.String namespaceName)
    {
        @selfRef.NamespaceName = namespaceName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs WithPartnerNamespace(this global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs @selfRef, global::System.String partnerNamespace)
    {
        @selfRef.PartnerNamespace = partnerNamespace;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs WithResourceGroupName(this global::Pulumi.AzureNative.ServiceBus.DisasterRecoveryConfigArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

}
