// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.Synapse;

public static partial class PrivateLinkHubArgsExtensions
{
    public static global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs WithLocation(this global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs WithPrivateLinkHubName(this global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs @selfRef, global::System.String privateLinkHubName)
    {
        @selfRef.PrivateLinkHubName = privateLinkHubName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs WithProvisioningState(this global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs @selfRef, global::System.String provisioningState)
    {
        @selfRef.ProvisioningState = provisioningState;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs WithResourceGroupName(this global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs WithTags(this global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs WithTags(this global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs WithTags(this global::Pulumi.AzureNative.Synapse.PrivateLinkHubArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
