// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Logic.Inputs;

namespace Pulumi.AzureNative.Logic;

public static partial class BusinessIdentityArgsExtensions
{
    public static global::Pulumi.AzureNative.Logic.Inputs.BusinessIdentityArgs WithQualifier(this global::Pulumi.AzureNative.Logic.Inputs.BusinessIdentityArgs @selfRef, global::System.String qualifier)
    {
        @selfRef.Qualifier = qualifier;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Logic.Inputs.BusinessIdentityArgs WithValue(this global::Pulumi.AzureNative.Logic.Inputs.BusinessIdentityArgs @selfRef, global::System.String value)
    {
        @selfRef.Value = value;
        return @selfRef;
    }

}
