// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.DataShare;

public static partial class SqlDBTableDataSetMappingArgsExtensions
{
    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithAccountName(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String accountName)
    {
        @selfRef.AccountName = accountName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithDataSetId(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String dataSetId)
    {
        @selfRef.DataSetId = dataSetId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithDataSetMappingName(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String dataSetMappingName)
    {
        @selfRef.DataSetMappingName = dataSetMappingName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithDatabaseName(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String databaseName)
    {
        @selfRef.DatabaseName = databaseName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithKind(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String kind)
    {
        @selfRef.Kind = kind;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithResourceGroupName(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithSchemaName(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String schemaName)
    {
        @selfRef.SchemaName = schemaName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithShareSubscriptionName(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String shareSubscriptionName)
    {
        @selfRef.ShareSubscriptionName = shareSubscriptionName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithSqlServerResourceId(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String sqlServerResourceId)
    {
        @selfRef.SqlServerResourceId = sqlServerResourceId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs WithTableName(this global::Pulumi.AzureNative.DataShare.SqlDBTableDataSetMappingArgs @selfRef, global::System.String tableName)
    {
        @selfRef.TableName = tableName;
        return @selfRef;
    }

}
