// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.CustomerInsights.Inputs;

namespace Pulumi.AzureNative.CustomerInsights;

public static partial class ConnectorMappingCompleteOperationArgsExtensions
{
    public static global::Pulumi.AzureNative.CustomerInsights.Inputs.ConnectorMappingCompleteOperationArgs WithCompletionOperationType(this global::Pulumi.AzureNative.CustomerInsights.Inputs.ConnectorMappingCompleteOperationArgs @selfRef, global::Pulumi.AzureNative.CustomerInsights.CompletionOperationTypes completionOperationType)
    {
        @selfRef.CompletionOperationType = completionOperationType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.CustomerInsights.Inputs.ConnectorMappingCompleteOperationArgs WithCompletionOperationType(this global::Pulumi.AzureNative.CustomerInsights.Inputs.ConnectorMappingCompleteOperationArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.CustomerInsights.CompletionOperationTypes> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AzureNative.CustomerInsights.CompletionOperationTypes>();
        @configure(@item);
        @selfRef.CompletionOperationType = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.CustomerInsights.Inputs.ConnectorMappingCompleteOperationArgs WithDestinationFolder(this global::Pulumi.AzureNative.CustomerInsights.Inputs.ConnectorMappingCompleteOperationArgs @selfRef, global::System.String destinationFolder)
    {
        @selfRef.DestinationFolder = destinationFolder;
        return @selfRef;
    }

}
