// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Monitor.Inputs;

namespace Pulumi.AzureNative.Monitor;

public static partial class ActionsArgsExtensions
{
    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithActionGroups(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Collections.Generic.List<global::System.String> actionGroups)
    {
        @selfRef.ActionGroups = actionGroups;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithActionGroups(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.ActionGroups = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithActionGroups(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.ActionGroups = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithActionProperties(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> actionProperties)
    {
        @selfRef.ActionProperties = actionProperties;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithActionProperties(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.ActionProperties = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithActionProperties(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.ActionProperties = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithCustomProperties(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> customProperties)
    {
        @selfRef.CustomProperties = customProperties;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithCustomProperties(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.CustomProperties = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs WithCustomProperties(this global::Pulumi.AzureNative.Monitor.Inputs.ActionsArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.CustomProperties = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
