// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Monitor.Inputs;

namespace Pulumi.AzureNative.Monitor;

public static partial class DynamicThresholdFailingPeriodsArgsExtensions
{
    public static global::Pulumi.AzureNative.Monitor.Inputs.DynamicThresholdFailingPeriodsArgs WithMinFailingPeriodsToAlert(this global::Pulumi.AzureNative.Monitor.Inputs.DynamicThresholdFailingPeriodsArgs @selfRef, global::System.Double minFailingPeriodsToAlert)
    {
        @selfRef.MinFailingPeriodsToAlert = minFailingPeriodsToAlert;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Monitor.Inputs.DynamicThresholdFailingPeriodsArgs WithNumberOfEvaluationPeriods(this global::Pulumi.AzureNative.Monitor.Inputs.DynamicThresholdFailingPeriodsArgs @selfRef, global::System.Double numberOfEvaluationPeriods)
    {
        @selfRef.NumberOfEvaluationPeriods = numberOfEvaluationPeriods;
        return @selfRef;
    }

}
