// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Amplify;

public static partial class AppArgsExtensions
{
    public static global::Pulumi.AwsNative.Amplify.AppArgs WithAccessToken(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String accessToken)
    {
        @selfRef.AccessToken = accessToken;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithAutoBranchCreationConfig(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::Pulumi.AwsNative.Amplify.Inputs.AppAutoBranchCreationConfigArgs autoBranchCreationConfig)
    {
        @selfRef.AutoBranchCreationConfig = autoBranchCreationConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithAutoBranchCreationConfig(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Amplify.Inputs.AppAutoBranchCreationConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Amplify.Inputs.AppAutoBranchCreationConfigArgs();
        @configure(@item);
        @selfRef.AutoBranchCreationConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithBasicAuthConfig(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::Pulumi.AwsNative.Amplify.Inputs.AppBasicAuthConfigArgs basicAuthConfig)
    {
        @selfRef.BasicAuthConfig = basicAuthConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithBasicAuthConfig(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Amplify.Inputs.AppBasicAuthConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Amplify.Inputs.AppBasicAuthConfigArgs();
        @configure(@item);
        @selfRef.BasicAuthConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithBuildSpec(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String buildSpec)
    {
        @selfRef.BuildSpec = buildSpec;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithCacheConfig(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::Pulumi.AwsNative.Amplify.Inputs.AppCacheConfigArgs cacheConfig)
    {
        @selfRef.CacheConfig = cacheConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithCacheConfig(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Amplify.Inputs.AppCacheConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Amplify.Inputs.AppCacheConfigArgs();
        @configure(@item);
        @selfRef.CacheConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithComputeRoleArn(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String computeRoleArn)
    {
        @selfRef.ComputeRoleArn = computeRoleArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithCustomHeaders(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String customHeaders)
    {
        @selfRef.CustomHeaders = customHeaders;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithCustomRules(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Amplify.Inputs.AppCustomRuleArgs> customRules)
    {
        @selfRef.CustomRules = customRules;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithCustomRules(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Amplify.Inputs.AppCustomRuleArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Amplify.Inputs.AppCustomRuleArgs>();
        @configure(@list);
        @selfRef.CustomRules = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithCustomRules(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Amplify.Inputs.AppCustomRuleArgs>> @create)
    {
        @selfRef.CustomRules = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithDescription(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithEnableBranchAutoDeletion(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, bool enableBranchAutoDeletion = true)
    {
        @selfRef.EnableBranchAutoDeletion = enableBranchAutoDeletion;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithEnvironmentVariables(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Amplify.Inputs.AppEnvironmentVariableArgs> environmentVariables)
    {
        @selfRef.EnvironmentVariables = environmentVariables;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithEnvironmentVariables(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Amplify.Inputs.AppEnvironmentVariableArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Amplify.Inputs.AppEnvironmentVariableArgs>();
        @configure(@list);
        @selfRef.EnvironmentVariables = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithEnvironmentVariables(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Amplify.Inputs.AppEnvironmentVariableArgs>> @create)
    {
        @selfRef.EnvironmentVariables = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithIamServiceRole(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String iamServiceRole)
    {
        @selfRef.IamServiceRole = iamServiceRole;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithName(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithOauthToken(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String oauthToken)
    {
        @selfRef.OauthToken = oauthToken;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithPlatform(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::Pulumi.AwsNative.Amplify.AppPlatform platform)
    {
        @selfRef.Platform = platform;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithPlatform(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Amplify.AppPlatform> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Amplify.AppPlatform>();
        @configure(@item);
        @selfRef.Platform = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithRepository(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.String repository)
    {
        @selfRef.Repository = repository;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithTags(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithTags(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>();
        @configure(@list);
        @selfRef.Tags = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Amplify.AppArgs WithTags(this global::Pulumi.AwsNative.Amplify.AppArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Inputs.TagArgs>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
