// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.VirtualMachineImages.Inputs;

namespace Pulumi.AzureNative.VirtualMachineImages;

public static partial class ImageTemplateSharedImageDistributorArgsExtensions
{
    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithArtifactTags(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> artifactTags)
    {
        @selfRef.ArtifactTags = artifactTags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithArtifactTags(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.ArtifactTags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithArtifactTags(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.ArtifactTags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithExcludeFromLatest(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, bool excludeFromLatest = true)
    {
        @selfRef.ExcludeFromLatest = excludeFromLatest;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithGalleryImageId(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.String galleryImageId)
    {
        @selfRef.GalleryImageId = galleryImageId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithReplicationRegions(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Collections.Generic.List<global::System.String> replicationRegions)
    {
        @selfRef.ReplicationRegions = replicationRegions;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithReplicationRegions(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.ReplicationRegions = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithReplicationRegions(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.ReplicationRegions = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithRunOutputName(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.String runOutputName)
    {
        @selfRef.RunOutputName = runOutputName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithStorageAccountType(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.VirtualMachineImages.SharedImageStorageAccountType> storageAccountType)
    {
        @selfRef.StorageAccountType = storageAccountType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithTargetRegions(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.VirtualMachineImages.Inputs.TargetRegionArgs> targetRegions)
    {
        @selfRef.TargetRegions = targetRegions;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithTargetRegions(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.VirtualMachineImages.Inputs.TargetRegionArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.VirtualMachineImages.Inputs.TargetRegionArgs>();
        @configure(@list);
        @selfRef.TargetRegions = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithTargetRegions(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.VirtualMachineImages.Inputs.TargetRegionArgs>> @create)
    {
        @selfRef.TargetRegions = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithType(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::System.String type)
    {
        @selfRef.Type = type;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs WithVersioning(this global::Pulumi.AzureNative.VirtualMachineImages.Inputs.ImageTemplateSharedImageDistributorArgs @selfRef, global::Pulumi.Union<global::Pulumi.AzureNative.VirtualMachineImages.Inputs.DistributeVersionerLatestArgs, global::Pulumi.AzureNative.VirtualMachineImages.Inputs.DistributeVersionerSourceArgs> versioning)
    {
        @selfRef.Versioning = versioning;
        return @selfRef;
    }

}
