// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AwsConnector.Inputs;

namespace Pulumi.AzureNative.AwsConnector;

public static partial class AwsEc2ImagePropertiesArgsExtensions
{
    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithArchitecture(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.ArchitectureValuesEnumValueArgs architecture)
    {
        @selfRef.Architecture = architecture;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithArchitecture(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.ArchitectureValuesEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.ArchitectureValuesEnumValueArgs();
        @configure(@item);
        @selfRef.Architecture = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithBlockDeviceMappings(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.BlockDeviceMappingArgs> blockDeviceMappings)
    {
        @selfRef.BlockDeviceMappings = blockDeviceMappings;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithBlockDeviceMappings(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.BlockDeviceMappingArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.BlockDeviceMappingArgs>();
        @configure(@list);
        @selfRef.BlockDeviceMappings = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithBlockDeviceMappings(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.AwsConnector.Inputs.BlockDeviceMappingArgs>> @create)
    {
        @selfRef.BlockDeviceMappings = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithBootMode(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.BootModeValuesEnumValueArgs bootMode)
    {
        @selfRef.BootMode = bootMode;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithBootMode(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.BootModeValuesEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.BootModeValuesEnumValueArgs();
        @configure(@item);
        @selfRef.BootMode = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithCreationDate(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String creationDate)
    {
        @selfRef.CreationDate = creationDate;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithDeprecationTime(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String deprecationTime)
    {
        @selfRef.DeprecationTime = deprecationTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithDeregistrationProtection(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String deregistrationProtection)
    {
        @selfRef.DeregistrationProtection = deregistrationProtection;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithDescription(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithEnaSupport(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, bool enaSupport = true)
    {
        @selfRef.EnaSupport = enaSupport;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithHypervisor(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.HypervisorTypeEnumValueArgs hypervisor)
    {
        @selfRef.Hypervisor = hypervisor;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithHypervisor(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.HypervisorTypeEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.HypervisorTypeEnumValueArgs();
        @configure(@item);
        @selfRef.Hypervisor = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithImageId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String imageId)
    {
        @selfRef.ImageId = imageId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithImageLocation(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String imageLocation)
    {
        @selfRef.ImageLocation = imageLocation;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithImageOwnerAlias(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String imageOwnerAlias)
    {
        @selfRef.ImageOwnerAlias = imageOwnerAlias;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithImageType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.ImageTypeValuesEnumValueArgs imageType)
    {
        @selfRef.ImageType = imageType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithImageType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.ImageTypeValuesEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.ImageTypeValuesEnumValueArgs();
        @configure(@item);
        @selfRef.ImageType = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithImdsSupport(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.ImdsSupportValuesEnumValueArgs imdsSupport)
    {
        @selfRef.ImdsSupport = imdsSupport;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithImdsSupport(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.ImdsSupportValuesEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.ImdsSupportValuesEnumValueArgs();
        @configure(@item);
        @selfRef.ImdsSupport = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithKernelId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String kernelId)
    {
        @selfRef.KernelId = kernelId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithLastLaunchedTime(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String lastLaunchedTime)
    {
        @selfRef.LastLaunchedTime = lastLaunchedTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithName(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithOwnerId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String ownerId)
    {
        @selfRef.OwnerId = ownerId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithPlatform(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.PlatformValuesEnumValueArgs platform)
    {
        @selfRef.Platform = platform;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithPlatform(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.PlatformValuesEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.PlatformValuesEnumValueArgs();
        @configure(@item);
        @selfRef.Platform = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithPlatformDetails(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String platformDetails)
    {
        @selfRef.PlatformDetails = platformDetails;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithProductCodes(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.ProductCodeArgs> productCodes)
    {
        @selfRef.ProductCodes = productCodes;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithProductCodes(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.ProductCodeArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.ProductCodeArgs>();
        @configure(@list);
        @selfRef.ProductCodes = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithProductCodes(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.AwsConnector.Inputs.ProductCodeArgs>> @create)
    {
        @selfRef.ProductCodes = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithPublic(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, bool @public = true)
    {
        @selfRef.Public = @public;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithRamdiskId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String ramdiskId)
    {
        @selfRef.RamdiskId = ramdiskId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithRootDeviceName(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String rootDeviceName)
    {
        @selfRef.RootDeviceName = rootDeviceName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithRootDeviceType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.DeviceTypeEnumValueArgs rootDeviceType)
    {
        @selfRef.RootDeviceType = rootDeviceType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithRootDeviceType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.DeviceTypeEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.DeviceTypeEnumValueArgs();
        @configure(@item);
        @selfRef.RootDeviceType = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithSourceInstanceId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String sourceInstanceId)
    {
        @selfRef.SourceInstanceId = sourceInstanceId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithSriovNetSupport(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String sriovNetSupport)
    {
        @selfRef.SriovNetSupport = sriovNetSupport;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithState(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.ImageStateEnumValueArgs state)
    {
        @selfRef.State = state;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithState(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.ImageStateEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.ImageStateEnumValueArgs();
        @configure(@item);
        @selfRef.State = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithStateReason(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.StateReasonArgs stateReason)
    {
        @selfRef.StateReason = stateReason;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithStateReason(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.StateReasonArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.StateReasonArgs();
        @configure(@item);
        @selfRef.StateReason = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithTags(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithTags(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs>();
        @configure(@list);
        @selfRef.Tags = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithTags(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithTpmSupport(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.TpmSupportValuesEnumValueArgs tpmSupport)
    {
        @selfRef.TpmSupport = tpmSupport;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithTpmSupport(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.TpmSupportValuesEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.TpmSupportValuesEnumValueArgs();
        @configure(@item);
        @selfRef.TpmSupport = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithUsageOperation(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.String usageOperation)
    {
        @selfRef.UsageOperation = usageOperation;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithVirtualizationType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.VirtualizationTypeEnumValueArgs virtualizationType)
    {
        @selfRef.VirtualizationType = virtualizationType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs WithVirtualizationType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsEc2ImagePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.VirtualizationTypeEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.VirtualizationTypeEnumValueArgs();
        @configure(@item);
        @selfRef.VirtualizationType = @item;
        return @selfRef;
    }

}
