// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AwsConnector.Inputs;

namespace Pulumi.AzureNative.AwsConnector;

public static partial class AwsRdsDBSnapshotPropertiesArgsExtensions
{
    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithAllocatedStorage(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Int32 allocatedStorage)
    {
        @selfRef.AllocatedStorage = allocatedStorage;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithAvailabilityZone(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String availabilityZone)
    {
        @selfRef.AvailabilityZone = availabilityZone;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithDbInstanceIdentifier(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String dbInstanceIdentifier)
    {
        @selfRef.DbInstanceIdentifier = dbInstanceIdentifier;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithDbSnapshotArn(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String dbSnapshotArn)
    {
        @selfRef.DbSnapshotArn = dbSnapshotArn;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithDbSnapshotIdentifier(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String dbSnapshotIdentifier)
    {
        @selfRef.DbSnapshotIdentifier = dbSnapshotIdentifier;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithDbSystemId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String dbSystemId)
    {
        @selfRef.DbSystemId = dbSystemId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithDbiResourceId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String dbiResourceId)
    {
        @selfRef.DbiResourceId = dbiResourceId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithDedicatedLogVolume(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, bool dedicatedLogVolume = true)
    {
        @selfRef.DedicatedLogVolume = dedicatedLogVolume;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithEncrypted(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, bool encrypted = true)
    {
        @selfRef.Encrypted = encrypted;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithEngine(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String engine)
    {
        @selfRef.Engine = engine;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithEngineVersion(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String engineVersion)
    {
        @selfRef.EngineVersion = engineVersion;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithIamDatabaseAuthenticationEnabled(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, bool iamDatabaseAuthenticationEnabled = true)
    {
        @selfRef.IamDatabaseAuthenticationEnabled = iamDatabaseAuthenticationEnabled;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithInstanceCreateTime(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String instanceCreateTime)
    {
        @selfRef.InstanceCreateTime = instanceCreateTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithIops(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Int32 iops)
    {
        @selfRef.Iops = iops;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithKmsKeyId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String kmsKeyId)
    {
        @selfRef.KmsKeyId = kmsKeyId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithLicenseModel(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String licenseModel)
    {
        @selfRef.LicenseModel = licenseModel;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithMasterUsername(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String masterUsername)
    {
        @selfRef.MasterUsername = masterUsername;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithMultiTenant(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, bool multiTenant = true)
    {
        @selfRef.MultiTenant = multiTenant;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithOptionGroupName(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String optionGroupName)
    {
        @selfRef.OptionGroupName = optionGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithOriginalSnapshotCreateTime(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String originalSnapshotCreateTime)
    {
        @selfRef.OriginalSnapshotCreateTime = originalSnapshotCreateTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithPercentProgress(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Int32 percentProgress)
    {
        @selfRef.PercentProgress = percentProgress;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithPort(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Int32 port)
    {
        @selfRef.Port = port;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithProcessorFeatures(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.ProcessorFeatureArgs> processorFeatures)
    {
        @selfRef.ProcessorFeatures = processorFeatures;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithProcessorFeatures(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.ProcessorFeatureArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.ProcessorFeatureArgs>();
        @configure(@list);
        @selfRef.ProcessorFeatures = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithProcessorFeatures(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.AwsConnector.Inputs.ProcessorFeatureArgs>> @create)
    {
        @selfRef.ProcessorFeatures = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithSnapshotCreateTime(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String snapshotCreateTime)
    {
        @selfRef.SnapshotCreateTime = snapshotCreateTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithSnapshotDatabaseTime(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String snapshotDatabaseTime)
    {
        @selfRef.SnapshotDatabaseTime = snapshotDatabaseTime;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithSnapshotTarget(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String snapshotTarget)
    {
        @selfRef.SnapshotTarget = snapshotTarget;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithSnapshotType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String snapshotType)
    {
        @selfRef.SnapshotType = snapshotType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithSourceDBSnapshotIdentifier(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String sourceDBSnapshotIdentifier)
    {
        @selfRef.SourceDBSnapshotIdentifier = sourceDBSnapshotIdentifier;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithSourceRegion(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String sourceRegion)
    {
        @selfRef.SourceRegion = sourceRegion;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithStatus(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String status)
    {
        @selfRef.Status = status;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithStorageThroughput(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Int32 storageThroughput)
    {
        @selfRef.StorageThroughput = storageThroughput;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithStorageType(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String storageType)
    {
        @selfRef.StorageType = storageType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithTagList(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs> tagList)
    {
        @selfRef.TagList = tagList;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithTagList(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs>();
        @configure(@list);
        @selfRef.TagList = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithTagList(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.AwsConnector.Inputs.TagArgs>> @create)
    {
        @selfRef.TagList = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithTdeCredentialArn(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String tdeCredentialArn)
    {
        @selfRef.TdeCredentialArn = tdeCredentialArn;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithTimezone(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String timezone)
    {
        @selfRef.Timezone = timezone;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs WithVpcId(this global::Pulumi.AzureNative.AwsConnector.Inputs.AwsRdsDBSnapshotPropertiesArgs @selfRef, global::System.String vpcId)
    {
        @selfRef.VpcId = vpcId;
        return @selfRef;
    }

}
