// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.AwsConnector;

public static partial class EcsClusterArgsExtensions
{
    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithLocation(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithName(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithProperties(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.EcsClusterPropertiesArgs properties)
    {
        @selfRef.Properties = properties;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithProperties(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.EcsClusterPropertiesArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.EcsClusterPropertiesArgs();
        @configure(@item);
        @selfRef.Properties = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithResourceGroupName(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithTags(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithTags(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs WithTags(this global::Pulumi.AzureNative.AwsConnector.EcsClusterArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
