// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AwsConnector.Inputs;

namespace Pulumi.AzureNative.AwsConnector;

public static partial class InstanceIpv4PrefixArgsExtensions
{
    public static global::Pulumi.AzureNative.AwsConnector.Inputs.InstanceIpv4PrefixArgs WithIpv4Prefix(this global::Pulumi.AzureNative.AwsConnector.Inputs.InstanceIpv4PrefixArgs @selfRef, global::System.String ipv4Prefix)
    {
        @selfRef.Ipv4Prefix = ipv4Prefix;
        return @selfRef;
    }

}
