// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AwsConnector.Inputs;

namespace Pulumi.AzureNative.AwsConnector;

public static partial class PlacementGroupConfigArgsExtensions
{
    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs WithInstanceRole(this global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.InstanceRoleTypeEnumValueArgs instanceRole)
    {
        @selfRef.InstanceRole = instanceRole;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs WithInstanceRole(this global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.InstanceRoleTypeEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.InstanceRoleTypeEnumValueArgs();
        @configure(@item);
        @selfRef.InstanceRole = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs WithPlacementStrategy(this global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs @selfRef, global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupStrategyEnumValueArgs placementStrategy)
    {
        @selfRef.PlacementStrategy = placementStrategy;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs WithPlacementStrategy(this global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupConfigArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupStrategyEnumValueArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AwsConnector.Inputs.PlacementGroupStrategyEnumValueArgs();
        @configure(@item);
        @selfRef.PlacementStrategy = @item;
        return @selfRef;
    }

}
