// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AwsConnector.Inputs;

namespace Pulumi.AzureNative.AwsConnector;

public static partial class PortArgsExtensions
{
    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithAccessDirection(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.String accessDirection)
    {
        @selfRef.AccessDirection = accessDirection;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithAccessFrom(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.String accessFrom)
    {
        @selfRef.AccessFrom = accessFrom;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithAccessType(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.String accessType)
    {
        @selfRef.AccessType = accessType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithCidrListAliases(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Collections.Generic.List<global::System.String> cidrListAliases)
    {
        @selfRef.CidrListAliases = cidrListAliases;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithCidrListAliases(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.CidrListAliases = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithCidrListAliases(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.CidrListAliases = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithCidrs(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Collections.Generic.List<global::System.String> cidrs)
    {
        @selfRef.Cidrs = cidrs;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithCidrs(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Cidrs = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithCidrs(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Cidrs = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithCommonName(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.String commonName)
    {
        @selfRef.CommonName = commonName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithFromPort(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Int32 fromPort)
    {
        @selfRef.FromPort = fromPort;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithIpv6Cidrs(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Collections.Generic.List<global::System.String> ipv6Cidrs)
    {
        @selfRef.Ipv6Cidrs = ipv6Cidrs;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithIpv6Cidrs(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Ipv6Cidrs = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithIpv6Cidrs(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Ipv6Cidrs = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithProtocol(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.String protocol)
    {
        @selfRef.Protocol = protocol;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs WithToPort(this global::Pulumi.AzureNative.AwsConnector.Inputs.PortArgs @selfRef, global::System.Int32 toPort)
    {
        @selfRef.ToPort = toPort;
        return @selfRef;
    }

}
