// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.DataMigration.Inputs;

namespace Pulumi.AzureNative.DataMigration;

public static partial class MigrateMySqlAzureDbForMySqlOfflineTaskInputArgsExtensions
{
    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithEncryptedKeyForSecureFields(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.String encryptedKeyForSecureFields)
    {
        @selfRef.EncryptedKeyForSecureFields = encryptedKeyForSecureFields;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithMakeSourceServerReadOnly(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, bool makeSourceServerReadOnly = true)
    {
        @selfRef.MakeSourceServerReadOnly = makeSourceServerReadOnly;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithOptionalAgentSettings(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> optionalAgentSettings)
    {
        @selfRef.OptionalAgentSettings = optionalAgentSettings;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithOptionalAgentSettings(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.OptionalAgentSettings = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithOptionalAgentSettings(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.OptionalAgentSettings = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithSelectedDatabases(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineDatabaseInputArgs> selectedDatabases)
    {
        @selfRef.SelectedDatabases = selectedDatabases;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithSelectedDatabases(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineDatabaseInputArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineDatabaseInputArgs>();
        @configure(@list);
        @selfRef.SelectedDatabases = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithSelectedDatabases(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineDatabaseInputArgs>> @create)
    {
        @selfRef.SelectedDatabases = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithSourceConnectionInfo(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::Pulumi.AzureNative.DataMigration.Inputs.MySqlConnectionInfoArgs sourceConnectionInfo)
    {
        @selfRef.SourceConnectionInfo = sourceConnectionInfo;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithSourceConnectionInfo(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DataMigration.Inputs.MySqlConnectionInfoArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DataMigration.Inputs.MySqlConnectionInfoArgs();
        @configure(@item);
        @selfRef.SourceConnectionInfo = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithStartedOn(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.String startedOn)
    {
        @selfRef.StartedOn = startedOn;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithTargetConnectionInfo(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::Pulumi.AzureNative.DataMigration.Inputs.MySqlConnectionInfoArgs targetConnectionInfo)
    {
        @selfRef.TargetConnectionInfo = targetConnectionInfo;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs WithTargetConnectionInfo(this global::Pulumi.AzureNative.DataMigration.Inputs.MigrateMySqlAzureDbForMySqlOfflineTaskInputArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DataMigration.Inputs.MySqlConnectionInfoArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DataMigration.Inputs.MySqlConnectionInfoArgs();
        @configure(@item);
        @selfRef.TargetConnectionInfo = @item;
        return @selfRef;
    }

}
