// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Cognito;

public static partial class UserPoolIdentityProviderArgsExtensions
{
    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithAttributeMapping(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> attributeMapping)
    {
        @selfRef.AttributeMapping = attributeMapping;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithAttributeMapping(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.AttributeMapping = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithAttributeMapping(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.AttributeMapping = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithIdpIdentifiers(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Collections.Generic.List<global::System.String> idpIdentifiers)
    {
        @selfRef.IdpIdentifiers = idpIdentifiers;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithIdpIdentifiers(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.IdpIdentifiers = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithIdpIdentifiers(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.IdpIdentifiers = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithProviderDetails(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> providerDetails)
    {
        @selfRef.ProviderDetails = providerDetails;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithProviderDetails(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.ProviderDetails = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithProviderDetails(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.ProviderDetails = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithProviderName(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.String providerName)
    {
        @selfRef.ProviderName = providerName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithProviderType(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.String providerType)
    {
        @selfRef.ProviderType = providerType;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs WithUserPoolId(this global::Pulumi.AwsNative.Cognito.UserPoolIdentityProviderArgs @selfRef, global::System.String userPoolId)
    {
        @selfRef.UserPoolId = userPoolId;
        return @selfRef;
    }

}
