// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Batch.Inputs;

namespace Pulumi.AwsNative.Batch;

public static partial class ComputeEnvironmentUpdatePolicyArgsExtensions
{
    public static global::Pulumi.AwsNative.Batch.Inputs.ComputeEnvironmentUpdatePolicyArgs WithJobExecutionTimeoutMinutes(this global::Pulumi.AwsNative.Batch.Inputs.ComputeEnvironmentUpdatePolicyArgs @selfRef, global::System.Int32 jobExecutionTimeoutMinutes)
    {
        @selfRef.JobExecutionTimeoutMinutes = jobExecutionTimeoutMinutes;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Batch.Inputs.ComputeEnvironmentUpdatePolicyArgs WithTerminateJobsOnUpdate(this global::Pulumi.AwsNative.Batch.Inputs.ComputeEnvironmentUpdatePolicyArgs @selfRef, bool terminateJobsOnUpdate = true)
    {
        @selfRef.TerminateJobsOnUpdate = terminateJobsOnUpdate;
        return @selfRef;
    }

}
