// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Batch.Inputs;

namespace Pulumi.AwsNative.Batch;

public static partial class JobQueueJobStateTimeLimitActionArgsExtensions
{
    public static global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs WithAction(this global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs @selfRef, global::Pulumi.AwsNative.Batch.JobQueueJobStateTimeLimitActionAction action)
    {
        @selfRef.Action = action;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs WithAction(this global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Batch.JobQueueJobStateTimeLimitActionAction> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Batch.JobQueueJobStateTimeLimitActionAction>();
        @configure(@item);
        @selfRef.Action = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs WithMaxTimeSeconds(this global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs @selfRef, global::System.Int32 maxTimeSeconds)
    {
        @selfRef.MaxTimeSeconds = maxTimeSeconds;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs WithReason(this global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs @selfRef, global::System.String reason)
    {
        @selfRef.Reason = reason;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs WithState(this global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs @selfRef, global::Pulumi.AwsNative.Batch.JobQueueJobStateTimeLimitActionState state)
    {
        @selfRef.State = state;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs WithState(this global::Pulumi.AwsNative.Batch.Inputs.JobQueueJobStateTimeLimitActionArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Batch.JobQueueJobStateTimeLimitActionState> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Batch.JobQueueJobStateTimeLimitActionState>();
        @configure(@item);
        @selfRef.State = @item;
        return @selfRef;
    }

}
