// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.MediaLive;

public static partial class MultiplexArgsExtensions
{
    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithAvailabilityZones(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Collections.Generic.List<global::System.String> availabilityZones)
    {
        @selfRef.AvailabilityZones = availabilityZones;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithAvailabilityZones(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.AvailabilityZones = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithAvailabilityZones(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.AvailabilityZones = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithDestinations(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.MediaLive.Inputs.MultiplexOutputDestinationArgs> destinations)
    {
        @selfRef.Destinations = destinations;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithDestinations(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.MediaLive.Inputs.MultiplexOutputDestinationArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.MediaLive.Inputs.MultiplexOutputDestinationArgs>();
        @configure(@list);
        @selfRef.Destinations = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithDestinations(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.MediaLive.Inputs.MultiplexOutputDestinationArgs>> @create)
    {
        @selfRef.Destinations = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithMultiplexSettings(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::Pulumi.AwsNative.MediaLive.Inputs.MultiplexSettingsArgs multiplexSettings)
    {
        @selfRef.MultiplexSettings = multiplexSettings;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithMultiplexSettings(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.MediaLive.Inputs.MultiplexSettingsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.MediaLive.Inputs.MultiplexSettingsArgs();
        @configure(@item);
        @selfRef.MultiplexSettings = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithName(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithTags(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithTags(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>();
        @configure(@list);
        @selfRef.Tags = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.MediaLive.MultiplexArgs WithTags(this global::Pulumi.AwsNative.MediaLive.MultiplexArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Inputs.TagArgs>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
