// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.S3.Inputs;

namespace Pulumi.AwsNative.S3;

public static partial class BucketOwnershipControlsRuleArgsExtensions
{
    public static global::Pulumi.AwsNative.S3.Inputs.BucketOwnershipControlsRuleArgs WithObjectOwnership(this global::Pulumi.AwsNative.S3.Inputs.BucketOwnershipControlsRuleArgs @selfRef, global::Pulumi.AwsNative.S3.BucketOwnershipControlsRuleObjectOwnership objectOwnership)
    {
        @selfRef.ObjectOwnership = objectOwnership;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.S3.Inputs.BucketOwnershipControlsRuleArgs WithObjectOwnership(this global::Pulumi.AwsNative.S3.Inputs.BucketOwnershipControlsRuleArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.S3.BucketOwnershipControlsRuleObjectOwnership> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.S3.BucketOwnershipControlsRuleObjectOwnership>();
        @configure(@item);
        @selfRef.ObjectOwnership = @item;
        return @selfRef;
    }

}
