// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.LakeFormation;

public static partial class TagAssociationArgsExtensions
{
    public static global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs WithLfTags(this global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.LakeFormation.Inputs.TagAssociationLfTagPairArgs> lfTags)
    {
        @selfRef.LfTags = lfTags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs WithLfTags(this global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.LakeFormation.Inputs.TagAssociationLfTagPairArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.LakeFormation.Inputs.TagAssociationLfTagPairArgs>();
        @configure(@list);
        @selfRef.LfTags = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs WithLfTags(this global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.LakeFormation.Inputs.TagAssociationLfTagPairArgs>> @create)
    {
        @selfRef.LfTags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs WithResource(this global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs @selfRef, global::Pulumi.AwsNative.LakeFormation.Inputs.TagAssociationResourceArgs resource)
    {
        @selfRef.Resource = resource;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs WithResource(this global::Pulumi.AwsNative.LakeFormation.TagAssociationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.LakeFormation.Inputs.TagAssociationResourceArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.LakeFormation.Inputs.TagAssociationResourceArgs();
        @configure(@item);
        @selfRef.Resource = @item;
        return @selfRef;
    }

}
