// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.CloudFront.Inputs;

namespace Pulumi.AwsNative.CloudFront;

public static partial class ResponseHeadersPolicyFrameOptionsArgsExtensions
{
    public static global::Pulumi.AwsNative.CloudFront.Inputs.ResponseHeadersPolicyFrameOptionsArgs WithFrameOption(this global::Pulumi.AwsNative.CloudFront.Inputs.ResponseHeadersPolicyFrameOptionsArgs @selfRef, global::System.String frameOption)
    {
        @selfRef.FrameOption = frameOption;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.CloudFront.Inputs.ResponseHeadersPolicyFrameOptionsArgs WithOverride(this global::Pulumi.AwsNative.CloudFront.Inputs.ResponseHeadersPolicyFrameOptionsArgs @selfRef, bool @override = true)
    {
        @selfRef.Override = @override;
        return @selfRef;
    }

}
