// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Ec2;

public static partial class RouteServerAssociationArgsExtensions
{
    public static global::Pulumi.AwsNative.Ec2.RouteServerAssociationArgs WithRouteServerId(this global::Pulumi.AwsNative.Ec2.RouteServerAssociationArgs @selfRef, global::System.String routeServerId)
    {
        @selfRef.RouteServerId = routeServerId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Ec2.RouteServerAssociationArgs WithVpcId(this global::Pulumi.AwsNative.Ec2.RouteServerAssociationArgs @selfRef, global::System.String vpcId)
    {
        @selfRef.VpcId = vpcId;
        return @selfRef;
    }

}
