// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Ec2.Inputs;

namespace Pulumi.AwsNative.Ec2;

public static partial class SpotFleetClassicLoadBalancersConfigArgsExtensions
{
    public static global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancersConfigArgs WithClassicLoadBalancers(this global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancersConfigArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancerArgs> classicLoadBalancers)
    {
        @selfRef.ClassicLoadBalancers = classicLoadBalancers;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancersConfigArgs WithClassicLoadBalancers(this global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancersConfigArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancerArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancerArgs>();
        @configure(@list);
        @selfRef.ClassicLoadBalancers = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancersConfigArgs WithClassicLoadBalancers(this global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancersConfigArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Ec2.Inputs.SpotFleetClassicLoadBalancerArgs>> @create)
    {
        @selfRef.ClassicLoadBalancers = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
