// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.QBusiness;

public static partial class RetrieverExtensions
{

    extension(Retriever)
    {
        public static Retriever New(string @id, global::Pulumi.AwsNative.QBusiness.RetrieverArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new Retriever(@id, @args, @options);
        }

        public static Retriever New(string @id, global::System.Action<global::Pulumi.AwsNative.QBusiness.RetrieverArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AwsNative.QBusiness.RetrieverArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new Retriever(@id, @args, @options);
        }

    }

}
