// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Lambda;

public static partial class EventSourceMappingArgsExtensions
{
    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithAmazonManagedKafkaEventSourceConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingAmazonManagedKafkaEventSourceConfigArgs amazonManagedKafkaEventSourceConfig)
    {
        @selfRef.AmazonManagedKafkaEventSourceConfig = amazonManagedKafkaEventSourceConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithAmazonManagedKafkaEventSourceConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingAmazonManagedKafkaEventSourceConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingAmazonManagedKafkaEventSourceConfigArgs();
        @configure(@item);
        @selfRef.AmazonManagedKafkaEventSourceConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithBatchSize(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Int32 batchSize)
    {
        @selfRef.BatchSize = batchSize;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithBisectBatchOnFunctionError(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, bool bisectBatchOnFunctionError = true)
    {
        @selfRef.BisectBatchOnFunctionError = bisectBatchOnFunctionError;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithDestinationConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingDestinationConfigArgs destinationConfig)
    {
        @selfRef.DestinationConfig = destinationConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithDestinationConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingDestinationConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingDestinationConfigArgs();
        @configure(@item);
        @selfRef.DestinationConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithDocumentDbEventSourceConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingDocumentDbEventSourceConfigArgs documentDbEventSourceConfig)
    {
        @selfRef.DocumentDbEventSourceConfig = documentDbEventSourceConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithDocumentDbEventSourceConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingDocumentDbEventSourceConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingDocumentDbEventSourceConfigArgs();
        @configure(@item);
        @selfRef.DocumentDbEventSourceConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithEnabled(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, bool enabled = true)
    {
        @selfRef.Enabled = enabled;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithEventSourceArn(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.String eventSourceArn)
    {
        @selfRef.EventSourceArn = eventSourceArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithFilterCriteria(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingFilterCriteriaArgs filterCriteria)
    {
        @selfRef.FilterCriteria = filterCriteria;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithFilterCriteria(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingFilterCriteriaArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingFilterCriteriaArgs();
        @configure(@item);
        @selfRef.FilterCriteria = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithFunctionName(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.String functionName)
    {
        @selfRef.FunctionName = functionName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithFunctionResponseTypes(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lambda.EventSourceMappingFunctionResponseTypesItem> functionResponseTypes)
    {
        @selfRef.FunctionResponseTypes = functionResponseTypes;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithFunctionResponseTypes(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lambda.EventSourceMappingFunctionResponseTypesItem>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lambda.EventSourceMappingFunctionResponseTypesItem>();
        @configure(@list);
        @selfRef.FunctionResponseTypes = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithFunctionResponseTypes(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Lambda.EventSourceMappingFunctionResponseTypesItem>> @create)
    {
        @selfRef.FunctionResponseTypes = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithKmsKeyArn(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.String kmsKeyArn)
    {
        @selfRef.KmsKeyArn = kmsKeyArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithMaximumBatchingWindowInSeconds(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Int32 maximumBatchingWindowInSeconds)
    {
        @selfRef.MaximumBatchingWindowInSeconds = maximumBatchingWindowInSeconds;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithMaximumRecordAgeInSeconds(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Int32 maximumRecordAgeInSeconds)
    {
        @selfRef.MaximumRecordAgeInSeconds = maximumRecordAgeInSeconds;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithMaximumRetryAttempts(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Int32 maximumRetryAttempts)
    {
        @selfRef.MaximumRetryAttempts = maximumRetryAttempts;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithMetricsConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingMetricsConfigArgs metricsConfig)
    {
        @selfRef.MetricsConfig = metricsConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithMetricsConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingMetricsConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingMetricsConfigArgs();
        @configure(@item);
        @selfRef.MetricsConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithParallelizationFactor(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Int32 parallelizationFactor)
    {
        @selfRef.ParallelizationFactor = parallelizationFactor;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithProvisionedPollerConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingProvisionedPollerConfigArgs provisionedPollerConfig)
    {
        @selfRef.ProvisionedPollerConfig = provisionedPollerConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithProvisionedPollerConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingProvisionedPollerConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingProvisionedPollerConfigArgs();
        @configure(@item);
        @selfRef.ProvisionedPollerConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithQueues(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Collections.Generic.List<global::System.String> queues)
    {
        @selfRef.Queues = queues;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithQueues(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Queues = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithQueues(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Queues = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithScalingConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingScalingConfigArgs scalingConfig)
    {
        @selfRef.ScalingConfig = scalingConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithScalingConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingScalingConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingScalingConfigArgs();
        @configure(@item);
        @selfRef.ScalingConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithSelfManagedEventSource(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSelfManagedEventSourceArgs selfManagedEventSource)
    {
        @selfRef.SelfManagedEventSource = selfManagedEventSource;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithSelfManagedEventSource(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSelfManagedEventSourceArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSelfManagedEventSourceArgs();
        @configure(@item);
        @selfRef.SelfManagedEventSource = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithSelfManagedKafkaEventSourceConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSelfManagedKafkaEventSourceConfigArgs selfManagedKafkaEventSourceConfig)
    {
        @selfRef.SelfManagedKafkaEventSourceConfig = selfManagedKafkaEventSourceConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithSelfManagedKafkaEventSourceConfig(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSelfManagedKafkaEventSourceConfigArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSelfManagedKafkaEventSourceConfigArgs();
        @configure(@item);
        @selfRef.SelfManagedKafkaEventSourceConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithSourceAccessConfigurations(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSourceAccessConfigurationArgs> sourceAccessConfigurations)
    {
        @selfRef.SourceAccessConfigurations = sourceAccessConfigurations;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithSourceAccessConfigurations(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSourceAccessConfigurationArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSourceAccessConfigurationArgs>();
        @configure(@list);
        @selfRef.SourceAccessConfigurations = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithSourceAccessConfigurations(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Lambda.Inputs.EventSourceMappingSourceAccessConfigurationArgs>> @create)
    {
        @selfRef.SourceAccessConfigurations = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithStartingPosition(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.String startingPosition)
    {
        @selfRef.StartingPosition = startingPosition;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithStartingPositionTimestamp(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Double startingPositionTimestamp)
    {
        @selfRef.StartingPositionTimestamp = startingPositionTimestamp;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithTags(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithTags(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>();
        @configure(@list);
        @selfRef.Tags = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithTags(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Inputs.TagArgs>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithTopics(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Collections.Generic.List<global::System.String> topics)
    {
        @selfRef.Topics = topics;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithTopics(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Topics = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithTopics(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Topics = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs WithTumblingWindowInSeconds(this global::Pulumi.AwsNative.Lambda.EventSourceMappingArgs @selfRef, global::System.Int32 tumblingWindowInSeconds)
    {
        @selfRef.TumblingWindowInSeconds = tumblingWindowInSeconds;
        return @selfRef;
    }

}
