// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Lambda;

public static partial class LayerVersionPermissionArgsExtensions
{
    public static global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs WithAction(this global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs @selfRef, global::System.String action)
    {
        @selfRef.Action = action;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs WithLayerVersionArn(this global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs @selfRef, global::System.String layerVersionArn)
    {
        @selfRef.LayerVersionArn = layerVersionArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs WithOrganizationId(this global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs @selfRef, global::System.String organizationId)
    {
        @selfRef.OrganizationId = organizationId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs WithPrincipal(this global::Pulumi.AwsNative.Lambda.LayerVersionPermissionArgs @selfRef, global::System.String principal)
    {
        @selfRef.Principal = principal;
        return @selfRef;
    }

}
