// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.SecurityLake;

public static partial class SubscriberArgsExtensions
{
    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithAccessTypes(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.SecurityLake.SubscriberAccessTypesItem> accessTypes)
    {
        @selfRef.AccessTypes = accessTypes;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithAccessTypes(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.SecurityLake.SubscriberAccessTypesItem>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.SecurityLake.SubscriberAccessTypesItem>();
        @configure(@list);
        @selfRef.AccessTypes = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithAccessTypes(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.SecurityLake.SubscriberAccessTypesItem>> @create)
    {
        @selfRef.AccessTypes = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithDataLakeArn(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.String dataLakeArn)
    {
        @selfRef.DataLakeArn = dataLakeArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithSources(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.SecurityLake.Inputs.SubscriberSourceArgs> sources)
    {
        @selfRef.Sources = sources;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithSources(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.SecurityLake.Inputs.SubscriberSourceArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.SecurityLake.Inputs.SubscriberSourceArgs>();
        @configure(@list);
        @selfRef.Sources = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithSources(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.SecurityLake.Inputs.SubscriberSourceArgs>> @create)
    {
        @selfRef.Sources = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithSubscriberDescription(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.String subscriberDescription)
    {
        @selfRef.SubscriberDescription = subscriberDescription;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithSubscriberIdentity(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::Pulumi.AwsNative.SecurityLake.Inputs.SubscriberIdentityPropertiesArgs subscriberIdentity)
    {
        @selfRef.SubscriberIdentity = subscriberIdentity;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithSubscriberIdentity(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.SecurityLake.Inputs.SubscriberIdentityPropertiesArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.SecurityLake.Inputs.SubscriberIdentityPropertiesArgs();
        @configure(@item);
        @selfRef.SubscriberIdentity = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithSubscriberName(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.String subscriberName)
    {
        @selfRef.SubscriberName = subscriberName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithTags(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithTags(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Inputs.TagArgs>();
        @configure(@list);
        @selfRef.Tags = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityLake.SubscriberArgs WithTags(this global::Pulumi.AwsNative.SecurityLake.SubscriberArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Inputs.TagArgs>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
