// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.CustomerProfiles.Inputs;

namespace Pulumi.AwsNative.CustomerProfiles;

public static partial class EventTriggerConditionArgsExtensions
{
    public static global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs WithEventTriggerDimensions(this global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerDimensionArgs> eventTriggerDimensions)
    {
        @selfRef.EventTriggerDimensions = eventTriggerDimensions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs WithEventTriggerDimensions(this global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerDimensionArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerDimensionArgs>();
        @configure(@list);
        @selfRef.EventTriggerDimensions = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs WithEventTriggerDimensions(this global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerDimensionArgs>> @create)
    {
        @selfRef.EventTriggerDimensions = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs WithLogicalOperator(this global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs @selfRef, global::Pulumi.AwsNative.CustomerProfiles.EventTriggerLogicalOperator logicalOperator)
    {
        @selfRef.LogicalOperator = logicalOperator;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs WithLogicalOperator(this global::Pulumi.AwsNative.CustomerProfiles.Inputs.EventTriggerConditionArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.CustomerProfiles.EventTriggerLogicalOperator> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.CustomerProfiles.EventTriggerLogicalOperator>();
        @configure(@item);
        @selfRef.LogicalOperator = @item;
        return @selfRef;
    }

}
