// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class AnalysisGeospatialNullDataSettingsArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisGeospatialNullDataSettingsArgs WithSymbolStyle(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisGeospatialNullDataSettingsArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisGeospatialNullSymbolStyleArgs symbolStyle)
    {
        @selfRef.SymbolStyle = symbolStyle;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisGeospatialNullDataSettingsArgs WithSymbolStyle(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisGeospatialNullDataSettingsArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisGeospatialNullSymbolStyleArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisGeospatialNullSymbolStyleArgs();
        @configure(@item);
        @selfRef.SymbolStyle = @item;
        return @selfRef;
    }

}
