// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class AnalysisTableConditionalFormattingOptionArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs WithCell(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableCellConditionalFormattingArgs cell)
    {
        @selfRef.Cell = cell;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs WithCell(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableCellConditionalFormattingArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableCellConditionalFormattingArgs();
        @configure(@item);
        @selfRef.Cell = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs WithRow(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableRowConditionalFormattingArgs row)
    {
        @selfRef.Row = row;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs WithRow(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableConditionalFormattingOptionArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableRowConditionalFormattingArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTableRowConditionalFormattingArgs();
        @configure(@item);
        @selfRef.Row = @item;
        return @selfRef;
    }

}
