// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class AnalysisSheetImageStaticFileSourceArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisSheetImageStaticFileSourceArgs WithStaticFileId(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisSheetImageStaticFileSourceArgs @selfRef, global::System.String staticFileId)
    {
        @selfRef.StaticFileId = staticFileId;
        return @selfRef;
    }

}
