// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class AnalysisBarChartConfigurationArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithBarsArrangement(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.AnalysisBarsArrangement barsArrangement)
    {
        @selfRef.BarsArrangement = barsArrangement;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithBarsArrangement(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.AnalysisBarsArrangement> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.AnalysisBarsArrangement>();
        @configure(@item);
        @selfRef.BarsArrangement = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithCategoryAxis(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAxisDisplayOptionsArgs categoryAxis)
    {
        @selfRef.CategoryAxis = categoryAxis;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithCategoryAxis(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAxisDisplayOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAxisDisplayOptionsArgs();
        @configure(@item);
        @selfRef.CategoryAxis = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithCategoryLabelOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs categoryLabelOptions)
    {
        @selfRef.CategoryLabelOptions = categoryLabelOptions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithCategoryLabelOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs();
        @configure(@item);
        @selfRef.CategoryLabelOptions = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithColorLabelOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs colorLabelOptions)
    {
        @selfRef.ColorLabelOptions = colorLabelOptions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithColorLabelOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs();
        @configure(@item);
        @selfRef.ColorLabelOptions = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithContributionAnalysisDefaults(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisContributionAnalysisDefaultArgs> contributionAnalysisDefaults)
    {
        @selfRef.ContributionAnalysisDefaults = contributionAnalysisDefaults;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithContributionAnalysisDefaults(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisContributionAnalysisDefaultArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisContributionAnalysisDefaultArgs>();
        @configure(@list);
        @selfRef.ContributionAnalysisDefaults = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithContributionAnalysisDefaults(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisContributionAnalysisDefaultArgs>> @create)
    {
        @selfRef.ContributionAnalysisDefaults = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithDataLabels(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisDataLabelOptionsArgs dataLabels)
    {
        @selfRef.DataLabels = dataLabels;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithDataLabels(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisDataLabelOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisDataLabelOptionsArgs();
        @configure(@item);
        @selfRef.DataLabels = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithFieldWells(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartFieldWellsArgs fieldWells)
    {
        @selfRef.FieldWells = fieldWells;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithFieldWells(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartFieldWellsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartFieldWellsArgs();
        @configure(@item);
        @selfRef.FieldWells = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithInteractions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisVisualInteractionOptionsArgs interactions)
    {
        @selfRef.Interactions = interactions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithInteractions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisVisualInteractionOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisVisualInteractionOptionsArgs();
        @configure(@item);
        @selfRef.Interactions = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithLegend(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisLegendOptionsArgs legend)
    {
        @selfRef.Legend = legend;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithLegend(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisLegendOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisLegendOptionsArgs();
        @configure(@item);
        @selfRef.Legend = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithOrientation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.AnalysisBarChartOrientation orientation)
    {
        @selfRef.Orientation = orientation;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithOrientation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.AnalysisBarChartOrientation> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.AnalysisBarChartOrientation>();
        @configure(@item);
        @selfRef.Orientation = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithReferenceLines(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisReferenceLineArgs> referenceLines)
    {
        @selfRef.ReferenceLines = referenceLines;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithReferenceLines(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisReferenceLineArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisReferenceLineArgs>();
        @configure(@list);
        @selfRef.ReferenceLines = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithReferenceLines(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisReferenceLineArgs>> @create)
    {
        @selfRef.ReferenceLines = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithSmallMultiplesOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisSmallMultiplesOptionsArgs smallMultiplesOptions)
    {
        @selfRef.SmallMultiplesOptions = smallMultiplesOptions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithSmallMultiplesOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisSmallMultiplesOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisSmallMultiplesOptionsArgs();
        @configure(@item);
        @selfRef.SmallMultiplesOptions = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithSortConfiguration(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartSortConfigurationArgs sortConfiguration)
    {
        @selfRef.SortConfiguration = sortConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithSortConfiguration(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartSortConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartSortConfigurationArgs();
        @configure(@item);
        @selfRef.SortConfiguration = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithTooltip(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTooltipOptionsArgs tooltip)
    {
        @selfRef.Tooltip = tooltip;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithTooltip(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTooltipOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisTooltipOptionsArgs();
        @configure(@item);
        @selfRef.Tooltip = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithValueAxis(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAxisDisplayOptionsArgs valueAxis)
    {
        @selfRef.ValueAxis = valueAxis;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithValueAxis(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAxisDisplayOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAxisDisplayOptionsArgs();
        @configure(@item);
        @selfRef.ValueAxis = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithValueLabelOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs valueLabelOptions)
    {
        @selfRef.ValueLabelOptions = valueLabelOptions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithValueLabelOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisChartAxisLabelOptionsArgs();
        @configure(@item);
        @selfRef.ValueLabelOptions = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithVisualPalette(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisVisualPaletteArgs visualPalette)
    {
        @selfRef.VisualPalette = visualPalette;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs WithVisualPalette(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisBarChartConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisVisualPaletteArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisVisualPaletteArgs();
        @configure(@item);
        @selfRef.VisualPalette = @item;
        return @selfRef;
    }

}
