// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class AnalysisColumnTooltipItemArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithAggregation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAggregationFunctionArgs aggregation)
    {
        @selfRef.Aggregation = aggregation;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithAggregation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAggregationFunctionArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisAggregationFunctionArgs();
        @configure(@item);
        @selfRef.Aggregation = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithColumn(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnIdentifierArgs column)
    {
        @selfRef.Column = column;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithColumn(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnIdentifierArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnIdentifierArgs();
        @configure(@item);
        @selfRef.Column = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithLabel(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::System.String label)
    {
        @selfRef.Label = label;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithTooltipTarget(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::Pulumi.AwsNative.QuickSight.AnalysisTooltipTarget tooltipTarget)
    {
        @selfRef.TooltipTarget = tooltipTarget;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithTooltipTarget(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.AnalysisTooltipTarget> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.AnalysisTooltipTarget>();
        @configure(@item);
        @selfRef.TooltipTarget = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithVisibility(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::Pulumi.AwsNative.QuickSight.AnalysisVisibility visibility)
    {
        @selfRef.Visibility = visibility;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs WithVisibility(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisColumnTooltipItemArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.AnalysisVisibility> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.AnalysisVisibility>();
        @configure(@item);
        @selfRef.Visibility = @item;
        return @selfRef;
    }

}
