// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class AnalysisNumericalAggregationFunctionArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs WithPercentileAggregation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisPercentileAggregationArgs percentileAggregation)
    {
        @selfRef.PercentileAggregation = percentileAggregation;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs WithPercentileAggregation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisPercentileAggregationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisPercentileAggregationArgs();
        @configure(@item);
        @selfRef.PercentileAggregation = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs WithSimpleNumericalAggregation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs @selfRef, global::Pulumi.AwsNative.QuickSight.AnalysisSimpleNumericalAggregationFunction simpleNumericalAggregation)
    {
        @selfRef.SimpleNumericalAggregation = simpleNumericalAggregation;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs WithSimpleNumericalAggregation(this global::Pulumi.AwsNative.QuickSight.Inputs.AnalysisNumericalAggregationFunctionArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.AnalysisSimpleNumericalAggregationFunction> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.AnalysisSimpleNumericalAggregationFunction>();
        @configure(@item);
        @selfRef.SimpleNumericalAggregation = @item;
        return @selfRef;
    }

}
