// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class DashboardFilterRelativeDateTimeControlArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs WithCommitMode(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs @selfRef, global::Pulumi.AwsNative.QuickSight.DashboardCommitMode commitMode)
    {
        @selfRef.CommitMode = commitMode;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs WithCommitMode(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.DashboardCommitMode> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.DashboardCommitMode>();
        @configure(@item);
        @selfRef.CommitMode = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs WithDisplayOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.DashboardRelativeDateTimeControlDisplayOptionsArgs displayOptions)
    {
        @selfRef.DisplayOptions = displayOptions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs WithDisplayOptions(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.DashboardRelativeDateTimeControlDisplayOptionsArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.DashboardRelativeDateTimeControlDisplayOptionsArgs();
        @configure(@item);
        @selfRef.DisplayOptions = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs WithFilterControlId(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs @selfRef, global::System.String filterControlId)
    {
        @selfRef.FilterControlId = filterControlId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs WithSourceFilterId(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs @selfRef, global::System.String sourceFilterId)
    {
        @selfRef.SourceFilterId = sourceFilterId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs WithTitle(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardFilterRelativeDateTimeControlArgs @selfRef, global::System.String title)
    {
        @selfRef.Title = title;
        return @selfRef;
    }

}
