// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class DashboardDefaultInteractiveLayoutConfigurationArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs WithFreeForm(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultFreeFormLayoutConfigurationArgs freeForm)
    {
        @selfRef.FreeForm = freeForm;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs WithFreeForm(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultFreeFormLayoutConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultFreeFormLayoutConfigurationArgs();
        @configure(@item);
        @selfRef.FreeForm = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs WithGrid(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultGridLayoutConfigurationArgs grid)
    {
        @selfRef.Grid = grid;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs WithGrid(this global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultInteractiveLayoutConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultGridLayoutConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.DashboardDefaultGridLayoutConfigurationArgs();
        @configure(@item);
        @selfRef.Grid = @item;
        return @selfRef;
    }

}
