// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class DataSetGeoSpatialColumnGroupArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs WithColumns(this global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs @selfRef, global::System.Collections.Generic.List<global::System.String> columns)
    {
        @selfRef.Columns = columns;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs WithColumns(this global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Columns = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs WithColumns(this global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Columns = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs WithCountryCode(this global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs @selfRef, global::Pulumi.AwsNative.QuickSight.DataSetGeoSpatialCountryCode countryCode)
    {
        @selfRef.CountryCode = countryCode;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs WithCountryCode(this global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.DataSetGeoSpatialCountryCode> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.DataSetGeoSpatialCountryCode>();
        @configure(@item);
        @selfRef.CountryCode = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs WithName(this global::Pulumi.AwsNative.QuickSight.Inputs.DataSetGeoSpatialColumnGroupArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

}
