// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class TemplateEmptyVisualArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs WithActions(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateVisualCustomActionArgs> actions)
    {
        @selfRef.Actions = actions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs WithActions(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateVisualCustomActionArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateVisualCustomActionArgs>();
        @configure(@list);
        @selfRef.Actions = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs WithActions(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateVisualCustomActionArgs>> @create)
    {
        @selfRef.Actions = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs WithDataSetIdentifier(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs @selfRef, global::System.String dataSetIdentifier)
    {
        @selfRef.DataSetIdentifier = dataSetIdentifier;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs WithVisualId(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateEmptyVisualArgs @selfRef, global::System.String visualId)
    {
        @selfRef.VisualId = visualId;
        return @selfRef;
    }

}
