// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class TemplateThousandSeparatorOptionsArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs WithGroupingStyle(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs @selfRef, global::Pulumi.AwsNative.QuickSight.TemplateDigitGroupingStyle groupingStyle)
    {
        @selfRef.GroupingStyle = groupingStyle;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs WithGroupingStyle(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.TemplateDigitGroupingStyle> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.TemplateDigitGroupingStyle>();
        @configure(@item);
        @selfRef.GroupingStyle = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs WithSymbol(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs @selfRef, global::Pulumi.AwsNative.QuickSight.TemplateNumericSeparatorSymbol symbol)
    {
        @selfRef.Symbol = symbol;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs WithSymbol(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.TemplateNumericSeparatorSymbol> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.TemplateNumericSeparatorSymbol>();
        @configure(@item);
        @selfRef.Symbol = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs WithVisibility(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs @selfRef, global::System.Object visibility)
    {
        @selfRef.Visibility = visibility;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs WithVisibility(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateThousandSeparatorOptionsArgs @selfRef, global::System.Action<global::System.Object> @configure)
    {
        var @item = new global::System.Object();
        @configure(@item);
        @selfRef.Visibility = @item;
        return @selfRef;
    }

}
