// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class TemplateFilterGroupArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithCrossDataset(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::Pulumi.AwsNative.QuickSight.TemplateCrossDatasetTypes crossDataset)
    {
        @selfRef.CrossDataset = crossDataset;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithCrossDataset(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.TemplateCrossDatasetTypes> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.TemplateCrossDatasetTypes>();
        @configure(@item);
        @selfRef.CrossDataset = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithFilterGroupId(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::System.String filterGroupId)
    {
        @selfRef.FilterGroupId = filterGroupId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithFilters(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterArgs> filters)
    {
        @selfRef.Filters = filters;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithFilters(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterArgs>();
        @configure(@list);
        @selfRef.Filters = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithFilters(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterArgs>> @create)
    {
        @selfRef.Filters = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithScopeConfiguration(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterScopeConfigurationArgs scopeConfiguration)
    {
        @selfRef.ScopeConfiguration = scopeConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithScopeConfiguration(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterScopeConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterScopeConfigurationArgs();
        @configure(@item);
        @selfRef.ScopeConfiguration = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithStatus(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::Pulumi.AwsNative.QuickSight.TemplateWidgetStatus status)
    {
        @selfRef.Status = status;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs WithStatus(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateFilterGroupArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.TemplateWidgetStatus> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.QuickSight.TemplateWidgetStatus>();
        @configure(@item);
        @selfRef.Status = @item;
        return @selfRef;
    }

}
