// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.QuickSight.Inputs;

namespace Pulumi.AwsNative.QuickSight;

public static partial class TemplateNumericalDimensionFieldArgsExtensions
{
    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs WithColumn(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.TemplateColumnIdentifierArgs column)
    {
        @selfRef.Column = column;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs WithColumn(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateColumnIdentifierArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.TemplateColumnIdentifierArgs();
        @configure(@item);
        @selfRef.Column = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs WithFieldId(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs @selfRef, global::System.String fieldId)
    {
        @selfRef.FieldId = fieldId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs WithFormatConfiguration(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs @selfRef, global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumberFormatConfigurationArgs formatConfiguration)
    {
        @selfRef.FormatConfiguration = formatConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs WithFormatConfiguration(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumberFormatConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumberFormatConfigurationArgs();
        @configure(@item);
        @selfRef.FormatConfiguration = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs WithHierarchyId(this global::Pulumi.AwsNative.QuickSight.Inputs.TemplateNumericalDimensionFieldArgs @selfRef, global::System.String hierarchyId)
    {
        @selfRef.HierarchyId = hierarchyId;
        return @selfRef;
    }

}
