// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Web.Inputs;

namespace Pulumi.AzureNative.Web;

public static partial class CorsSettingsArgsExtensions
{
    public static global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs WithAllowedOrigins(this global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs @selfRef, global::System.Collections.Generic.List<global::System.String> allowedOrigins)
    {
        @selfRef.AllowedOrigins = allowedOrigins;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs WithAllowedOrigins(this global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.AllowedOrigins = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs WithAllowedOrigins(this global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.AllowedOrigins = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs WithSupportCredentials(this global::Pulumi.AzureNative.Web.Inputs.CorsSettingsArgs @selfRef, bool supportCredentials = true)
    {
        @selfRef.SupportCredentials = supportCredentials;
        return @selfRef;
    }

}
