// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.FrontDoor;

public static partial class PolicyArgsExtensions
{
    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithCustomRules(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::Pulumi.AzureNative.FrontDoor.Inputs.CustomRuleListArgs customRules)
    {
        @selfRef.CustomRules = customRules;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithCustomRules(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.FrontDoor.Inputs.CustomRuleListArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.FrontDoor.Inputs.CustomRuleListArgs();
        @configure(@item);
        @selfRef.CustomRules = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithLocation(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithManagedRules(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::Pulumi.AzureNative.FrontDoor.Inputs.ManagedRuleSetListArgs managedRules)
    {
        @selfRef.ManagedRules = managedRules;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithManagedRules(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.FrontDoor.Inputs.ManagedRuleSetListArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.FrontDoor.Inputs.ManagedRuleSetListArgs();
        @configure(@item);
        @selfRef.ManagedRules = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithPolicyName(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.String policyName)
    {
        @selfRef.PolicyName = policyName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithPolicySettings(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::Pulumi.AzureNative.FrontDoor.Inputs.PolicySettingsArgs policySettings)
    {
        @selfRef.PolicySettings = policySettings;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithPolicySettings(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.FrontDoor.Inputs.PolicySettingsArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.FrontDoor.Inputs.PolicySettingsArgs();
        @configure(@item);
        @selfRef.PolicySettings = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithResourceGroupName(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithSku(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::Pulumi.AzureNative.FrontDoor.Inputs.SkuArgs sku)
    {
        @selfRef.Sku = sku;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithSku(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.FrontDoor.Inputs.SkuArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.FrontDoor.Inputs.SkuArgs();
        @configure(@item);
        @selfRef.Sku = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithTags(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithTags(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.FrontDoor.PolicyArgs WithTags(this global::Pulumi.AzureNative.FrontDoor.PolicyArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
