// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.AzureStackHCI;

public static partial class GalleryImageArgsExtensions
{
    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithCloudInitDataSource(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.AzureStackHCI.CloudInitDataSource> cloudInitDataSource)
    {
        @selfRef.CloudInitDataSource = cloudInitDataSource;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithContainerId(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.String containerId)
    {
        @selfRef.ContainerId = containerId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithExtendedLocation(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::Pulumi.AzureNative.AzureStackHCI.Inputs.ExtendedLocationArgs extendedLocation)
    {
        @selfRef.ExtendedLocation = extendedLocation;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithExtendedLocation(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AzureStackHCI.Inputs.ExtendedLocationArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AzureStackHCI.Inputs.ExtendedLocationArgs();
        @configure(@item);
        @selfRef.ExtendedLocation = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithGalleryImageName(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.String galleryImageName)
    {
        @selfRef.GalleryImageName = galleryImageName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithHyperVGeneration(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.AzureStackHCI.HyperVGeneration> hyperVGeneration)
    {
        @selfRef.HyperVGeneration = hyperVGeneration;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithIdentifier(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::Pulumi.AzureNative.AzureStackHCI.Inputs.GalleryImageIdentifierArgs identifier)
    {
        @selfRef.Identifier = identifier;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithIdentifier(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AzureStackHCI.Inputs.GalleryImageIdentifierArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AzureStackHCI.Inputs.GalleryImageIdentifierArgs();
        @configure(@item);
        @selfRef.Identifier = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithImagePath(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.String imagePath)
    {
        @selfRef.ImagePath = imagePath;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithLocation(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithOsType(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.AzureStackHCI.OperatingSystemTypes> osType)
    {
        @selfRef.OsType = osType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithResourceGroupName(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithSourceVirtualMachineId(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.String sourceVirtualMachineId)
    {
        @selfRef.SourceVirtualMachineId = sourceVirtualMachineId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithTags(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithTags(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithTags(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithVersion(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::Pulumi.AzureNative.AzureStackHCI.Inputs.GalleryImageVersionArgs version)
    {
        @selfRef.Version = version;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithVersion(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AzureStackHCI.Inputs.GalleryImageVersionArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AzureStackHCI.Inputs.GalleryImageVersionArgs();
        @configure(@item);
        @selfRef.Version = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithVmImageRepositoryCredentials(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::Pulumi.AzureNative.AzureStackHCI.Inputs.VmImageRepositoryCredentialsArgs vmImageRepositoryCredentials)
    {
        @selfRef.VmImageRepositoryCredentials = vmImageRepositoryCredentials;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs WithVmImageRepositoryCredentials(this global::Pulumi.AzureNative.AzureStackHCI.GalleryImageArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AzureStackHCI.Inputs.VmImageRepositoryCredentialsArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.AzureStackHCI.Inputs.VmImageRepositoryCredentialsArgs();
        @configure(@item);
        @selfRef.VmImageRepositoryCredentials = @item;
        return @selfRef;
    }

}
