// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AzureStackHCI.Inputs;

namespace Pulumi.AzureNative.AzureStackHCI;

public static partial class InterfaceDNSSettingsArgsExtensions
{
    public static global::Pulumi.AzureNative.AzureStackHCI.Inputs.InterfaceDNSSettingsArgs WithDnsServers(this global::Pulumi.AzureNative.AzureStackHCI.Inputs.InterfaceDNSSettingsArgs @selfRef, global::System.Collections.Generic.List<global::System.String> dnsServers)
    {
        @selfRef.DnsServers = dnsServers;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.Inputs.InterfaceDNSSettingsArgs WithDnsServers(this global::Pulumi.AzureNative.AzureStackHCI.Inputs.InterfaceDNSSettingsArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.DnsServers = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureStackHCI.Inputs.InterfaceDNSSettingsArgs WithDnsServers(this global::Pulumi.AzureNative.AzureStackHCI.Inputs.InterfaceDNSSettingsArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.DnsServers = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
