// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.NetworkManager.Inputs;

namespace Pulumi.AwsNative.NetworkManager;

public static partial class VpcAttachmentProposedNetworkFunctionGroupChangeArgsExtensions
{
    public static global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs WithAttachmentPolicyRuleNumber(this global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs @selfRef, global::System.Int32 attachmentPolicyRuleNumber)
    {
        @selfRef.AttachmentPolicyRuleNumber = attachmentPolicyRuleNumber;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs WithNetworkFunctionGroupName(this global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs @selfRef, global::System.String networkFunctionGroupName)
    {
        @selfRef.NetworkFunctionGroupName = networkFunctionGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs WithTags(this global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentTagArgs> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs WithTags(this global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentTagArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentTagArgs>();
        @configure(@list);
        @selfRef.Tags = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs WithTags(this global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentProposedNetworkFunctionGroupChangeArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.NetworkManager.Inputs.VpcAttachmentTagArgs>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
