// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.WaFv2.Inputs;

namespace Pulumi.AwsNative.WaFv2;

public static partial class WebAclAwsManagedRulesBotControlRuleSetArgsExtensions
{
    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclAwsManagedRulesBotControlRuleSetArgs WithEnableMachineLearning(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclAwsManagedRulesBotControlRuleSetArgs @selfRef, bool enableMachineLearning = true)
    {
        @selfRef.EnableMachineLearning = enableMachineLearning;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclAwsManagedRulesBotControlRuleSetArgs WithInspectionLevel(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclAwsManagedRulesBotControlRuleSetArgs @selfRef, global::Pulumi.AwsNative.WaFv2.WebAclAwsManagedRulesBotControlRuleSetInspectionLevel inspectionLevel)
    {
        @selfRef.InspectionLevel = inspectionLevel;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclAwsManagedRulesBotControlRuleSetArgs WithInspectionLevel(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclAwsManagedRulesBotControlRuleSetArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.WaFv2.WebAclAwsManagedRulesBotControlRuleSetInspectionLevel> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.WaFv2.WebAclAwsManagedRulesBotControlRuleSetInspectionLevel>();
        @configure(@item);
        @selfRef.InspectionLevel = @item;
        return @selfRef;
    }

}
