// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.WaFv2.Inputs;

namespace Pulumi.AwsNative.WaFv2;

public static partial class WebAclRateBasedStatementArgsExtensions
{
    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithAggregateKeyType(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::Pulumi.AwsNative.WaFv2.WebAclRateBasedStatementAggregateKeyType aggregateKeyType)
    {
        @selfRef.AggregateKeyType = aggregateKeyType;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithAggregateKeyType(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.WaFv2.WebAclRateBasedStatementAggregateKeyType> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.WaFv2.WebAclRateBasedStatementAggregateKeyType>();
        @configure(@item);
        @selfRef.AggregateKeyType = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithCustomKeys(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementCustomKeyArgs> customKeys)
    {
        @selfRef.CustomKeys = customKeys;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithCustomKeys(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementCustomKeyArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementCustomKeyArgs>();
        @configure(@list);
        @selfRef.CustomKeys = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithCustomKeys(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementCustomKeyArgs>> @create)
    {
        @selfRef.CustomKeys = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithEvaluationWindowSec(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Int32 evaluationWindowSec)
    {
        @selfRef.EvaluationWindowSec = evaluationWindowSec;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithForwardedIpConfig(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::Pulumi.AwsNative.WaFv2.Inputs.WebAclForwardedIpConfigurationArgs forwardedIpConfig)
    {
        @selfRef.ForwardedIpConfig = forwardedIpConfig;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithForwardedIpConfig(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.WaFv2.Inputs.WebAclForwardedIpConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.WaFv2.Inputs.WebAclForwardedIpConfigurationArgs();
        @configure(@item);
        @selfRef.ForwardedIpConfig = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithLimit(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Int32 limit)
    {
        @selfRef.Limit = limit;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithScopeDownStatement(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::Pulumi.AwsNative.WaFv2.Inputs.WebAclStatementArgs scopeDownStatement)
    {
        @selfRef.ScopeDownStatement = scopeDownStatement;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs WithScopeDownStatement(this global::Pulumi.AwsNative.WaFv2.Inputs.WebAclRateBasedStatementArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.WaFv2.Inputs.WebAclStatementArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.WaFv2.Inputs.WebAclStatementArgs();
        @configure(@item);
        @selfRef.ScopeDownStatement = @item;
        return @selfRef;
    }

}
