// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.DataFactory.Inputs;

namespace Pulumi.AzureNative.DataFactory;

public static partial class PipelinePolicyArgsExtensions
{
    public static global::Pulumi.AzureNative.DataFactory.Inputs.PipelinePolicyArgs WithElapsedTimeMetric(this global::Pulumi.AzureNative.DataFactory.Inputs.PipelinePolicyArgs @selfRef, global::Pulumi.AzureNative.DataFactory.Inputs.PipelineElapsedTimeMetricPolicyArgs elapsedTimeMetric)
    {
        @selfRef.ElapsedTimeMetric = elapsedTimeMetric;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataFactory.Inputs.PipelinePolicyArgs WithElapsedTimeMetric(this global::Pulumi.AzureNative.DataFactory.Inputs.PipelinePolicyArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DataFactory.Inputs.PipelineElapsedTimeMetricPolicyArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DataFactory.Inputs.PipelineElapsedTimeMetricPolicyArgs();
        @configure(@item);
        @selfRef.ElapsedTimeMetric = @item;
        return @selfRef;
    }

}
