// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.DataProtection.Inputs;

namespace Pulumi.AzureNative.DataProtection;

public static partial class SourceLifeCycleArgsExtensions
{
    public static global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs WithDeleteAfter(this global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs @selfRef, global::Pulumi.AzureNative.DataProtection.Inputs.AbsoluteDeleteOptionArgs deleteAfter)
    {
        @selfRef.DeleteAfter = deleteAfter;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs WithDeleteAfter(this global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DataProtection.Inputs.AbsoluteDeleteOptionArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DataProtection.Inputs.AbsoluteDeleteOptionArgs();
        @configure(@item);
        @selfRef.DeleteAfter = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs WithSourceDataStore(this global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs @selfRef, global::Pulumi.AzureNative.DataProtection.Inputs.DataStoreInfoBaseArgs sourceDataStore)
    {
        @selfRef.SourceDataStore = sourceDataStore;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs WithSourceDataStore(this global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DataProtection.Inputs.DataStoreInfoBaseArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DataProtection.Inputs.DataStoreInfoBaseArgs();
        @configure(@item);
        @selfRef.SourceDataStore = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs WithTargetDataStoreCopySettings(this global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.DataProtection.Inputs.TargetCopySettingArgs> targetDataStoreCopySettings)
    {
        @selfRef.TargetDataStoreCopySettings = targetDataStoreCopySettings;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs WithTargetDataStoreCopySettings(this global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.DataProtection.Inputs.TargetCopySettingArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.DataProtection.Inputs.TargetCopySettingArgs>();
        @configure(@list);
        @selfRef.TargetDataStoreCopySettings = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs WithTargetDataStoreCopySettings(this global::Pulumi.AzureNative.DataProtection.Inputs.SourceLifeCycleArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.DataProtection.Inputs.TargetCopySettingArgs>> @create)
    {
        @selfRef.TargetDataStoreCopySettings = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
