// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Glue;

public static partial class JobExtensions
{

    extension(Job)
    {
        public static Job New(string @id, global::Pulumi.AwsNative.Glue.JobArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new Job(@id, @args, @options);
        }

        public static Job New(string @id, global::System.Action<global::Pulumi.AwsNative.Glue.JobArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AwsNative.Glue.JobArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new Job(@id, @args, @options);
        }

    }

}
