// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Bedrock;

public static partial class DataAutomationProjectExtensions
{

    extension(DataAutomationProject)
    {
        public static DataAutomationProject New(string @id, global::Pulumi.AwsNative.Bedrock.DataAutomationProjectArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new DataAutomationProject(@id, @args, @options);
        }

        public static DataAutomationProject New(string @id, global::System.Action<global::Pulumi.AwsNative.Bedrock.DataAutomationProjectArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AwsNative.Bedrock.DataAutomationProjectArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new DataAutomationProject(@id, @args, @options);
        }

    }

}
