// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Bedrock.Inputs;

namespace Pulumi.AwsNative.Bedrock;

public static partial class FlowAliasConcurrencyConfigurationArgsExtensions
{
    public static global::Pulumi.AwsNative.Bedrock.Inputs.FlowAliasConcurrencyConfigurationArgs WithMaxConcurrency(this global::Pulumi.AwsNative.Bedrock.Inputs.FlowAliasConcurrencyConfigurationArgs @selfRef, global::System.Double maxConcurrency)
    {
        @selfRef.MaxConcurrency = maxConcurrency;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Bedrock.Inputs.FlowAliasConcurrencyConfigurationArgs WithType(this global::Pulumi.AwsNative.Bedrock.Inputs.FlowAliasConcurrencyConfigurationArgs @selfRef, global::Pulumi.AwsNative.Bedrock.FlowAliasConcurrencyType type)
    {
        @selfRef.Type = type;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Bedrock.Inputs.FlowAliasConcurrencyConfigurationArgs WithType(this global::Pulumi.AwsNative.Bedrock.Inputs.FlowAliasConcurrencyConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Bedrock.FlowAliasConcurrencyType> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Bedrock.FlowAliasConcurrencyType>();
        @configure(@item);
        @selfRef.Type = @item;
        return @selfRef;
    }

}
