// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Bedrock.Inputs;

namespace Pulumi.AwsNative.Bedrock;

public static partial class FlowRerankingMetadataSelectiveModeConfiguration1PropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Bedrock.Inputs.FlowRerankingMetadataSelectiveModeConfiguration1PropertiesArgs WithFieldsToExclude(this global::Pulumi.AwsNative.Bedrock.Inputs.FlowRerankingMetadataSelectiveModeConfiguration1PropertiesArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Bedrock.Inputs.FlowFieldForRerankingArgs> fieldsToExclude)
    {
        @selfRef.FieldsToExclude = fieldsToExclude;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Bedrock.Inputs.FlowRerankingMetadataSelectiveModeConfiguration1PropertiesArgs WithFieldsToExclude(this global::Pulumi.AwsNative.Bedrock.Inputs.FlowRerankingMetadataSelectiveModeConfiguration1PropertiesArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Bedrock.Inputs.FlowFieldForRerankingArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Bedrock.Inputs.FlowFieldForRerankingArgs>();
        @configure(@list);
        @selfRef.FieldsToExclude = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Bedrock.Inputs.FlowRerankingMetadataSelectiveModeConfiguration1PropertiesArgs WithFieldsToExclude(this global::Pulumi.AwsNative.Bedrock.Inputs.FlowRerankingMetadataSelectiveModeConfiguration1PropertiesArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Bedrock.Inputs.FlowFieldForRerankingArgs>> @create)
    {
        @selfRef.FieldsToExclude = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
