// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Bedrock.Inputs;

namespace Pulumi.AwsNative.Bedrock;

public static partial class PromptTemplateConfiguration1PropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Bedrock.Inputs.PromptTemplateConfiguration1PropertiesArgs WithChat(this global::Pulumi.AwsNative.Bedrock.Inputs.PromptTemplateConfiguration1PropertiesArgs @selfRef, global::Pulumi.AwsNative.Bedrock.Inputs.PromptChatPromptTemplateConfigurationArgs chat)
    {
        @selfRef.Chat = chat;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Bedrock.Inputs.PromptTemplateConfiguration1PropertiesArgs WithChat(this global::Pulumi.AwsNative.Bedrock.Inputs.PromptTemplateConfiguration1PropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Bedrock.Inputs.PromptChatPromptTemplateConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Bedrock.Inputs.PromptChatPromptTemplateConfigurationArgs();
        @configure(@item);
        @selfRef.Chat = @item;
        return @selfRef;
    }

}
