// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.DataBrew.Inputs;

namespace Pulumi.AwsNative.DataBrew;

public static partial class DatasetPathParameterArgsExtensions
{
    public static global::Pulumi.AwsNative.DataBrew.Inputs.DatasetPathParameterArgs WithDatasetParameter(this global::Pulumi.AwsNative.DataBrew.Inputs.DatasetPathParameterArgs @selfRef, global::Pulumi.AwsNative.DataBrew.Inputs.DatasetParameterArgs datasetParameter)
    {
        @selfRef.DatasetParameter = datasetParameter;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.DataBrew.Inputs.DatasetPathParameterArgs WithDatasetParameter(this global::Pulumi.AwsNative.DataBrew.Inputs.DatasetPathParameterArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.DataBrew.Inputs.DatasetParameterArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.DataBrew.Inputs.DatasetParameterArgs();
        @configure(@item);
        @selfRef.DatasetParameter = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.DataBrew.Inputs.DatasetPathParameterArgs WithPathParameterName(this global::Pulumi.AwsNative.DataBrew.Inputs.DatasetPathParameterArgs @selfRef, global::System.String pathParameterName)
    {
        @selfRef.PathParameterName = pathParameterName;
        return @selfRef;
    }

}
