// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.HDInsight.Inputs;

namespace Pulumi.AzureNative.HDInsight;

public static partial class ScheduleBasedConfigArgsExtensions
{
    public static global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs WithDefaultCount(this global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs @selfRef, global::System.Int32 defaultCount)
    {
        @selfRef.DefaultCount = defaultCount;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs WithSchedules(this global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleArgs> schedules)
    {
        @selfRef.Schedules = schedules;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs WithSchedules(this global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleArgs>();
        @configure(@list);
        @selfRef.Schedules = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs WithSchedules(this global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleArgs>> @create)
    {
        @selfRef.Schedules = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs WithTimeZone(this global::Pulumi.AzureNative.HDInsight.Inputs.ScheduleBasedConfigArgs @selfRef, global::System.String timeZone)
    {
        @selfRef.TimeZone = timeZone;
        return @selfRef;
    }

}
