// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.DBforPostgreSQL;

public static partial class VirtualEndpointArgsExtensions
{
    public static global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs WithEndpointType(this global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointType> endpointType)
    {
        @selfRef.EndpointType = endpointType;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs WithMembers(this global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs @selfRef, global::System.Collections.Generic.List<global::System.String> members)
    {
        @selfRef.Members = members;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs WithMembers(this global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Members = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs WithMembers(this global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Members = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs WithResourceGroupName(this global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs WithServerName(this global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs @selfRef, global::System.String serverName)
    {
        @selfRef.ServerName = serverName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs WithVirtualEndpointName(this global::Pulumi.AzureNative.DBforPostgreSQL.VirtualEndpointArgs @selfRef, global::System.String virtualEndpointName)
    {
        @selfRef.VirtualEndpointName = virtualEndpointName;
        return @selfRef;
    }

}
