// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.AppRunner.Inputs;

namespace Pulumi.AwsNative.AppRunner;

public static partial class ServiceHealthCheckConfigurationArgsExtensions
{
    public static global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs WithHealthyThreshold(this global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs @selfRef, global::System.Int32 healthyThreshold)
    {
        @selfRef.HealthyThreshold = healthyThreshold;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs WithInterval(this global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs @selfRef, global::System.Int32 interval)
    {
        @selfRef.Interval = interval;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs WithPath(this global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs @selfRef, global::System.String path)
    {
        @selfRef.Path = path;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs WithProtocol(this global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs @selfRef, global::Pulumi.AwsNative.AppRunner.ServiceHealthCheckConfigurationProtocol protocol)
    {
        @selfRef.Protocol = protocol;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs WithProtocol(this global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.AppRunner.ServiceHealthCheckConfigurationProtocol> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.AppRunner.ServiceHealthCheckConfigurationProtocol>();
        @configure(@item);
        @selfRef.Protocol = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs WithTimeout(this global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs @selfRef, global::System.Int32 timeout)
    {
        @selfRef.Timeout = timeout;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs WithUnhealthyThreshold(this global::Pulumi.AwsNative.AppRunner.Inputs.ServiceHealthCheckConfigurationArgs @selfRef, global::System.Int32 unhealthyThreshold)
    {
        @selfRef.UnhealthyThreshold = unhealthyThreshold;
        return @selfRef;
    }

}
