// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Lex;

public static partial class BotVersionArgsExtensions
{
    public static global::Pulumi.AwsNative.Lex.BotVersionArgs WithBotId(this global::Pulumi.AwsNative.Lex.BotVersionArgs @selfRef, global::System.String botId)
    {
        @selfRef.BotId = botId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lex.BotVersionArgs WithBotVersionLocaleSpecification(this global::Pulumi.AwsNative.Lex.BotVersionArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lex.Inputs.BotVersionLocaleSpecificationArgs> botVersionLocaleSpecification)
    {
        @selfRef.BotVersionLocaleSpecification = botVersionLocaleSpecification;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lex.BotVersionArgs WithBotVersionLocaleSpecification(this global::Pulumi.AwsNative.Lex.BotVersionArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lex.Inputs.BotVersionLocaleSpecificationArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.Lex.Inputs.BotVersionLocaleSpecificationArgs>();
        @configure(@list);
        @selfRef.BotVersionLocaleSpecification = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lex.BotVersionArgs WithBotVersionLocaleSpecification(this global::Pulumi.AwsNative.Lex.BotVersionArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.Lex.Inputs.BotVersionLocaleSpecificationArgs>> @create)
    {
        @selfRef.BotVersionLocaleSpecification = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Lex.BotVersionArgs WithDescription(this global::Pulumi.AwsNative.Lex.BotVersionArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

}
