// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.ContainerRegistry.Inputs;

namespace Pulumi.AzureNative.ContainerRegistry;

public static partial class ExportPolicyArgsExtensions
{
    public static global::Pulumi.AzureNative.ContainerRegistry.Inputs.ExportPolicyArgs WithStatus(this global::Pulumi.AzureNative.ContainerRegistry.Inputs.ExportPolicyArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ContainerRegistry.ExportPolicyStatus> status)
    {
        @selfRef.Status = status;
        return @selfRef;
    }

}
