// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.ManagedIdentity;

public static partial class UserAssignedIdentityArgsExtensions
{
    public static global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs WithLocation(this global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs WithResourceGroupName(this global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs WithResourceName(this global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs @selfRef, global::System.String resourceName)
    {
        @selfRef.ResourceName = resourceName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs WithTags(this global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs WithTags(this global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs WithTags(this global::Pulumi.AzureNative.ManagedIdentity.UserAssignedIdentityArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
