// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.CosmosDB.Inputs;

namespace Pulumi.AzureNative.CosmosDB;

public static partial class MongoDBDatabaseResourceArgsExtensions
{
    public static global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs WithCreateMode(this global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.CosmosDB.CreateMode> createMode)
    {
        @selfRef.CreateMode = createMode;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs WithId(this global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs @selfRef, global::System.String id)
    {
        @selfRef.Id = id;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs WithRestoreParameters(this global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs @selfRef, global::Pulumi.AzureNative.CosmosDB.Inputs.ResourceRestoreParametersArgs restoreParameters)
    {
        @selfRef.RestoreParameters = restoreParameters;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs WithRestoreParameters(this global::Pulumi.AzureNative.CosmosDB.Inputs.MongoDBDatabaseResourceArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.CosmosDB.Inputs.ResourceRestoreParametersArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.CosmosDB.Inputs.ResourceRestoreParametersArgs();
        @configure(@item);
        @selfRef.RestoreParameters = @item;
        return @selfRef;
    }

}
