// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.OperationalInsights;

public static partial class SavedSearchExtensions
{

    extension(SavedSearch)
    {
        public static SavedSearch New(string @id, global::Pulumi.AzureNative.OperationalInsights.SavedSearchArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new SavedSearch(@id, @args, @options);
        }

        public static SavedSearch New(string @id, global::System.Action<global::Pulumi.AzureNative.OperationalInsights.SavedSearchArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AzureNative.OperationalInsights.SavedSearchArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new SavedSearch(@id, @args, @options);
        }

    }

}
