// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.TestBase.Inputs;

namespace Pulumi.AzureNative.TestBase;

public static partial class UserObjectReceiverValueArgsExtensions
{
    public static global::Pulumi.AzureNative.TestBase.Inputs.UserObjectReceiverValueArgs WithUserObjectIds(this global::Pulumi.AzureNative.TestBase.Inputs.UserObjectReceiverValueArgs @selfRef, global::System.Collections.Generic.List<global::System.String> userObjectIds)
    {
        @selfRef.UserObjectIds = userObjectIds;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.TestBase.Inputs.UserObjectReceiverValueArgs WithUserObjectIds(this global::Pulumi.AzureNative.TestBase.Inputs.UserObjectReceiverValueArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.UserObjectIds = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.TestBase.Inputs.UserObjectReceiverValueArgs WithUserObjectIds(this global::Pulumi.AzureNative.TestBase.Inputs.UserObjectReceiverValueArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.UserObjectIds = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
