// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Efs.Inputs;

namespace Pulumi.AwsNative.Efs;

public static partial class AccessPointCreationInfoArgsExtensions
{
    public static global::Pulumi.AwsNative.Efs.Inputs.AccessPointCreationInfoArgs WithOwnerGid(this global::Pulumi.AwsNative.Efs.Inputs.AccessPointCreationInfoArgs @selfRef, global::System.String ownerGid)
    {
        @selfRef.OwnerGid = ownerGid;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Efs.Inputs.AccessPointCreationInfoArgs WithOwnerUid(this global::Pulumi.AwsNative.Efs.Inputs.AccessPointCreationInfoArgs @selfRef, global::System.String ownerUid)
    {
        @selfRef.OwnerUid = ownerUid;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Efs.Inputs.AccessPointCreationInfoArgs WithPermissions(this global::Pulumi.AwsNative.Efs.Inputs.AccessPointCreationInfoArgs @selfRef, global::System.String permissions)
    {
        @selfRef.Permissions = permissions;
        return @selfRef;
    }

}
