// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.CostManagement.Inputs;

namespace Pulumi.AzureNative.CostManagement;

public static partial class ReportDeliveryInfoArgsExtensions
{
    public static global::Pulumi.AzureNative.CostManagement.Inputs.ReportDeliveryInfoArgs WithDestination(this global::Pulumi.AzureNative.CostManagement.Inputs.ReportDeliveryInfoArgs @selfRef, global::Pulumi.AzureNative.CostManagement.Inputs.ReportDeliveryDestinationArgs destination)
    {
        @selfRef.Destination = destination;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.CostManagement.Inputs.ReportDeliveryInfoArgs WithDestination(this global::Pulumi.AzureNative.CostManagement.Inputs.ReportDeliveryInfoArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.CostManagement.Inputs.ReportDeliveryDestinationArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.CostManagement.Inputs.ReportDeliveryDestinationArgs();
        @configure(@item);
        @selfRef.Destination = @item;
        return @selfRef;
    }

}
