// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.SecurityHub.Inputs;

namespace Pulumi.AwsNative.SecurityHub;

public static partial class AutomationRuleNoteUpdateArgsExtensions
{
    public static global::Pulumi.AwsNative.SecurityHub.Inputs.AutomationRuleNoteUpdateArgs WithText(this global::Pulumi.AwsNative.SecurityHub.Inputs.AutomationRuleNoteUpdateArgs @selfRef, global::System.String text)
    {
        @selfRef.Text = text;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SecurityHub.Inputs.AutomationRuleNoteUpdateArgs WithUpdatedBy(this global::Pulumi.AwsNative.SecurityHub.Inputs.AutomationRuleNoteUpdateArgs @selfRef, global::System.String updatedBy)
    {
        @selfRef.UpdatedBy = updatedBy;
        return @selfRef;
    }

}
