// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.EnterpriseKnowledgeGraph;

public static partial class EnterpriseKnowledgeGraphExtensions
{

    extension(EnterpriseKnowledgeGraph)
    {
        public static EnterpriseKnowledgeGraph New(string @id, global::Pulumi.AzureNative.EnterpriseKnowledgeGraph.EnterpriseKnowledgeGraphArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new EnterpriseKnowledgeGraph(@id, @args, @options);
        }

        public static EnterpriseKnowledgeGraph New(string @id, global::System.Action<global::Pulumi.AzureNative.EnterpriseKnowledgeGraph.EnterpriseKnowledgeGraphArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AzureNative.EnterpriseKnowledgeGraph.EnterpriseKnowledgeGraphArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new EnterpriseKnowledgeGraph(@id, @args, @options);
        }

    }

}
