// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.DataReplication.Inputs;

namespace Pulumi.AzureNative.DataReplication;

public static partial class ProtectedItemModelPropertiesArgsExtensions
{
    public static global::Pulumi.AzureNative.DataReplication.Inputs.ProtectedItemModelPropertiesArgs WithCustomProperties(this global::Pulumi.AzureNative.DataReplication.Inputs.ProtectedItemModelPropertiesArgs @selfRef, global::Pulumi.Union<global::Pulumi.AzureNative.DataReplication.Inputs.HyperVToAzStackHCIProtectedItemModelCustomPropertiesArgs, global::Pulumi.AzureNative.DataReplication.Inputs.VMwareToAzStackHCIProtectedItemModelCustomPropertiesArgs> customProperties)
    {
        @selfRef.CustomProperties = customProperties;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataReplication.Inputs.ProtectedItemModelPropertiesArgs WithPolicyName(this global::Pulumi.AzureNative.DataReplication.Inputs.ProtectedItemModelPropertiesArgs @selfRef, global::System.String policyName)
    {
        @selfRef.PolicyName = policyName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataReplication.Inputs.ProtectedItemModelPropertiesArgs WithReplicationExtensionName(this global::Pulumi.AzureNative.DataReplication.Inputs.ProtectedItemModelPropertiesArgs @selfRef, global::System.String replicationExtensionName)
    {
        @selfRef.ReplicationExtensionName = replicationExtensionName;
        return @selfRef;
    }

}
