// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Pipes.Inputs;

namespace Pulumi.AwsNative.Pipes;

public static partial class PipeSelfManagedKafkaAccessConfigurationCredentials3PropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Pipes.Inputs.PipeSelfManagedKafkaAccessConfigurationCredentials3PropertiesArgs WithClientCertificateTlsAuth(this global::Pulumi.AwsNative.Pipes.Inputs.PipeSelfManagedKafkaAccessConfigurationCredentials3PropertiesArgs @selfRef, global::System.String clientCertificateTlsAuth)
    {
        @selfRef.ClientCertificateTlsAuth = clientCertificateTlsAuth;
        return @selfRef;
    }

}
