// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.SageMaker.Inputs;

namespace Pulumi.AwsNative.SageMaker;

public static partial class ModelCardAdditionalInformationArgsExtensions
{
    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs WithCaveatsAndRecommendations(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs @selfRef, global::System.String caveatsAndRecommendations)
    {
        @selfRef.CaveatsAndRecommendations = caveatsAndRecommendations;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs WithCustomDetails(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> customDetails)
    {
        @selfRef.CustomDetails = customDetails;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs WithCustomDetails(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.CustomDetails = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs WithCustomDetails(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.CustomDetails = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs WithEthicalConsiderations(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardAdditionalInformationArgs @selfRef, global::System.String ethicalConsiderations)
    {
        @selfRef.EthicalConsiderations = ethicalConsiderations;
        return @selfRef;
    }

}
