// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.SageMaker.Inputs;

namespace Pulumi.AwsNative.SageMaker;

public static partial class ModelCardSimpleMetricArgsExtensions
{
    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs WithName(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs WithNotes(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs @selfRef, global::System.String notes)
    {
        @selfRef.Notes = notes;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs WithType(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs @selfRef, global::Pulumi.AwsNative.SageMaker.ModelCardSimpleMetricType type)
    {
        @selfRef.Type = type;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs WithType(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.SageMaker.ModelCardSimpleMetricType> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.SageMaker.ModelCardSimpleMetricType>();
        @configure(@item);
        @selfRef.Type = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs WithXAxisName(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs @selfRef, global::System.String xAxisName)
    {
        @selfRef.XAxisName = xAxisName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs WithYAxisName(this global::Pulumi.AwsNative.SageMaker.Inputs.ModelCardSimpleMetricArgs @selfRef, global::System.String yAxisName)
    {
        @selfRef.YAxisName = yAxisName;
        return @selfRef;
    }

}
