// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.SageMaker.Inputs;

namespace Pulumi.AwsNative.SageMaker;

public static partial class SpaceCustomFileSystemArgsExtensions
{
    public static global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs WithEfsFileSystem(this global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs @selfRef, global::Pulumi.AwsNative.SageMaker.Inputs.SpaceEfsFileSystemArgs efsFileSystem)
    {
        @selfRef.EfsFileSystem = efsFileSystem;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs WithEfsFileSystem(this global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.SageMaker.Inputs.SpaceEfsFileSystemArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.SageMaker.Inputs.SpaceEfsFileSystemArgs();
        @configure(@item);
        @selfRef.EfsFileSystem = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs WithFSxLustreFileSystem(this global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs @selfRef, global::Pulumi.AwsNative.SageMaker.Inputs.SpaceFSxLustreFileSystemArgs fSxLustreFileSystem)
    {
        @selfRef.FSxLustreFileSystem = fSxLustreFileSystem;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs WithFSxLustreFileSystem(this global::Pulumi.AwsNative.SageMaker.Inputs.SpaceCustomFileSystemArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.SageMaker.Inputs.SpaceFSxLustreFileSystemArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.SageMaker.Inputs.SpaceFSxLustreFileSystemArgs();
        @configure(@item);
        @selfRef.FSxLustreFileSystem = @item;
        return @selfRef;
    }

}
