// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Batch.Inputs;

namespace Pulumi.AzureNative.Batch;

public static partial class NetworkProfileArgsExtensions
{
    public static global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs WithAccountAccess(this global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs @selfRef, global::Pulumi.AzureNative.Batch.Inputs.EndpointAccessProfileArgs accountAccess)
    {
        @selfRef.AccountAccess = accountAccess;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs WithAccountAccess(this global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.Batch.Inputs.EndpointAccessProfileArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.Batch.Inputs.EndpointAccessProfileArgs();
        @configure(@item);
        @selfRef.AccountAccess = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs WithNodeManagementAccess(this global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs @selfRef, global::Pulumi.AzureNative.Batch.Inputs.EndpointAccessProfileArgs nodeManagementAccess)
    {
        @selfRef.NodeManagementAccess = nodeManagementAccess;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs WithNodeManagementAccess(this global::Pulumi.AzureNative.Batch.Inputs.NetworkProfileArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.Batch.Inputs.EndpointAccessProfileArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.Batch.Inputs.EndpointAccessProfileArgs();
        @configure(@item);
        @selfRef.NodeManagementAccess = @item;
        return @selfRef;
    }

}
