// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Aad.Inputs;

namespace Pulumi.AzureNative.Aad;

public static partial class NotificationSettingsArgsExtensions
{
    public static global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs WithAdditionalRecipients(this global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs @selfRef, global::System.Collections.Generic.List<global::System.String> additionalRecipients)
    {
        @selfRef.AdditionalRecipients = additionalRecipients;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs WithAdditionalRecipients(this global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.AdditionalRecipients = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs WithAdditionalRecipients(this global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.AdditionalRecipients = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs WithNotifyDcAdmins(this global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Aad.NotifyDcAdmins> notifyDcAdmins)
    {
        @selfRef.NotifyDcAdmins = notifyDcAdmins;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs WithNotifyGlobalAdmins(this global::Pulumi.AzureNative.Aad.Inputs.NotificationSettingsArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Aad.NotifyGlobalAdmins> notifyGlobalAdmins)
    {
        @selfRef.NotifyGlobalAdmins = notifyGlobalAdmins;
        return @selfRef;
    }

}
