// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.DatabaseWatcher.Inputs;

namespace Pulumi.AzureNative.DatabaseWatcher;

public static partial class DatastoreArgsExtensions
{
    public static global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs WithAdxClusterResourceId(this global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs @selfRef, global::System.String adxClusterResourceId)
    {
        @selfRef.AdxClusterResourceId = adxClusterResourceId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs WithKustoClusterDisplayName(this global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs @selfRef, global::System.String kustoClusterDisplayName)
    {
        @selfRef.KustoClusterDisplayName = kustoClusterDisplayName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs WithKustoClusterUri(this global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs @selfRef, global::System.String kustoClusterUri)
    {
        @selfRef.KustoClusterUri = kustoClusterUri;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs WithKustoDataIngestionUri(this global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs @selfRef, global::System.String kustoDataIngestionUri)
    {
        @selfRef.KustoDataIngestionUri = kustoDataIngestionUri;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs WithKustoDatabaseName(this global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs @selfRef, global::System.String kustoDatabaseName)
    {
        @selfRef.KustoDatabaseName = kustoDatabaseName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs WithKustoManagementUrl(this global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs @selfRef, global::System.String kustoManagementUrl)
    {
        @selfRef.KustoManagementUrl = kustoManagementUrl;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs WithKustoOfferingType(this global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.DatabaseWatcher.KustoOfferingType> kustoOfferingType)
    {
        @selfRef.KustoOfferingType = kustoOfferingType;
        return @selfRef;
    }

}
