// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.DatabaseWatcher;

public static partial class WatcherArgsExtensions
{
    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithDatastore(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs datastore)
    {
        @selfRef.Datastore = datastore;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithDatastore(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DatabaseWatcher.Inputs.DatastoreArgs();
        @configure(@item);
        @selfRef.Datastore = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithDefaultAlertRuleIdentityResourceId(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.String defaultAlertRuleIdentityResourceId)
    {
        @selfRef.DefaultAlertRuleIdentityResourceId = defaultAlertRuleIdentityResourceId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithIdentity(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::Pulumi.AzureNative.DatabaseWatcher.Inputs.ManagedServiceIdentityArgs identity)
    {
        @selfRef.Identity = identity;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithIdentity(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DatabaseWatcher.Inputs.ManagedServiceIdentityArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DatabaseWatcher.Inputs.ManagedServiceIdentityArgs();
        @configure(@item);
        @selfRef.Identity = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithLocation(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithResourceGroupName(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithTags(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithTags(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithTags(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs WithWatcherName(this global::Pulumi.AzureNative.DatabaseWatcher.WatcherArgs @selfRef, global::System.String watcherName)
    {
        @selfRef.WatcherName = watcherName;
        return @selfRef;
    }

}
