// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.InspectorV2.Inputs;

namespace Pulumi.AwsNative.InspectorV2;

public static partial class FilterNumberFilterArgsExtensions
{
    public static global::Pulumi.AwsNative.InspectorV2.Inputs.FilterNumberFilterArgs WithLowerInclusive(this global::Pulumi.AwsNative.InspectorV2.Inputs.FilterNumberFilterArgs @selfRef, global::System.Double lowerInclusive)
    {
        @selfRef.LowerInclusive = lowerInclusive;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.InspectorV2.Inputs.FilterNumberFilterArgs WithUpperInclusive(this global::Pulumi.AwsNative.InspectorV2.Inputs.FilterNumberFilterArgs @selfRef, global::System.Double upperInclusive)
    {
        @selfRef.UpperInclusive = upperInclusive;
        return @selfRef;
    }

}
