// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Cdn.Inputs;

namespace Pulumi.AzureNative.Cdn;

public static partial class RequestSchemeMatchConditionParametersArgsExtensions
{
    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithMatchValues(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.RequestSchemeMatchValue>> matchValues)
    {
        @selfRef.MatchValues = matchValues;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithMatchValues(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.RequestSchemeMatchValue>>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.RequestSchemeMatchValue>>();
        @configure(@list);
        @selfRef.MatchValues = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithMatchValues(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.RequestSchemeMatchValue>>> @create)
    {
        @selfRef.MatchValues = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithNegateCondition(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, bool negateCondition = true)
    {
        @selfRef.NegateCondition = negateCondition;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithOperator(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.String @operator)
    {
        @selfRef.Operator = @operator;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithTransforms(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.Transform>> transforms)
    {
        @selfRef.Transforms = transforms;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithTransforms(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.Transform>>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.Transform>>();
        @configure(@list);
        @selfRef.Transforms = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithTransforms(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Cdn.Transform>>> @create)
    {
        @selfRef.Transforms = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs WithTypeName(this global::Pulumi.AzureNative.Cdn.Inputs.RequestSchemeMatchConditionParametersArgs @selfRef, global::System.String typeName)
    {
        @selfRef.TypeName = typeName;
        return @selfRef;
    }

}
