// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.IoTOperations.Inputs;

namespace Pulumi.AzureNative.IoTOperations;

public static partial class ExtendedLocationArgsExtensions
{
    public static global::Pulumi.AzureNative.IoTOperations.Inputs.ExtendedLocationArgs WithName(this global::Pulumi.AzureNative.IoTOperations.Inputs.ExtendedLocationArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.IoTOperations.Inputs.ExtendedLocationArgs WithType(this global::Pulumi.AzureNative.IoTOperations.Inputs.ExtendedLocationArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.IoTOperations.ExtendedLocationType> type)
    {
        @selfRef.Type = type;
        return @selfRef;
    }

}
