// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.HybridNetwork.Inputs;

namespace Pulumi.AzureNative.HybridNetwork;

public static partial class LinuxConfigurationArgsExtensions
{
    public static global::Pulumi.AzureNative.HybridNetwork.Inputs.LinuxConfigurationArgs WithSsh(this global::Pulumi.AzureNative.HybridNetwork.Inputs.LinuxConfigurationArgs @selfRef, global::Pulumi.AzureNative.HybridNetwork.Inputs.SshConfigurationArgs ssh)
    {
        @selfRef.Ssh = ssh;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.HybridNetwork.Inputs.LinuxConfigurationArgs WithSsh(this global::Pulumi.AzureNative.HybridNetwork.Inputs.LinuxConfigurationArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.HybridNetwork.Inputs.SshConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.HybridNetwork.Inputs.SshConfigurationArgs();
        @configure(@item);
        @selfRef.Ssh = @item;
        return @selfRef;
    }

}
