// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.PcaConnectorScep;

public static partial class ChallengeArgsExtensions
{
    public static global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs WithConnectorArn(this global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs @selfRef, global::System.String connectorArn)
    {
        @selfRef.ConnectorArn = connectorArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs WithTags(this global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs WithTags(this global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs WithTags(this global::Pulumi.AwsNative.PcaConnectorScep.ChallengeArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
