// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.AccessAnalyzer.Inputs;

namespace Pulumi.AwsNative.AccessAnalyzer;

public static partial class AnalyzerConfigurationPropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.AccessAnalyzer.Inputs.AnalyzerConfigurationPropertiesArgs WithUnusedAccessConfiguration(this global::Pulumi.AwsNative.AccessAnalyzer.Inputs.AnalyzerConfigurationPropertiesArgs @selfRef, global::Pulumi.AwsNative.AccessAnalyzer.Inputs.AnalyzerUnusedAccessConfigurationArgs unusedAccessConfiguration)
    {
        @selfRef.UnusedAccessConfiguration = unusedAccessConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.AccessAnalyzer.Inputs.AnalyzerConfigurationPropertiesArgs WithUnusedAccessConfiguration(this global::Pulumi.AwsNative.AccessAnalyzer.Inputs.AnalyzerConfigurationPropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.AccessAnalyzer.Inputs.AnalyzerUnusedAccessConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.AccessAnalyzer.Inputs.AnalyzerUnusedAccessConfigurationArgs();
        @configure(@item);
        @selfRef.UnusedAccessConfiguration = @item;
        return @selfRef;
    }

}
