// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.OpenSearchService.Inputs;

namespace Pulumi.AwsNative.OpenSearchService;

public static partial class DomainIdpArgsExtensions
{
    public static global::Pulumi.AwsNative.OpenSearchService.Inputs.DomainIdpArgs WithEntityId(this global::Pulumi.AwsNative.OpenSearchService.Inputs.DomainIdpArgs @selfRef, global::System.String entityId)
    {
        @selfRef.EntityId = entityId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.OpenSearchService.Inputs.DomainIdpArgs WithMetadataContent(this global::Pulumi.AwsNative.OpenSearchService.Inputs.DomainIdpArgs @selfRef, global::System.String metadataContent)
    {
        @selfRef.MetadataContent = metadataContent;
        return @selfRef;
    }

}
