// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.ApiCenter.Inputs;

namespace Pulumi.AzureNative.ApiCenter;

public static partial class LicenseArgsExtensions
{
    public static global::Pulumi.AzureNative.ApiCenter.Inputs.LicenseArgs WithIdentifier(this global::Pulumi.AzureNative.ApiCenter.Inputs.LicenseArgs @selfRef, global::System.String identifier)
    {
        @selfRef.Identifier = identifier;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApiCenter.Inputs.LicenseArgs WithName(this global::Pulumi.AzureNative.ApiCenter.Inputs.LicenseArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApiCenter.Inputs.LicenseArgs WithUrl(this global::Pulumi.AzureNative.ApiCenter.Inputs.LicenseArgs @selfRef, global::System.String url)
    {
        @selfRef.Url = url;
        return @selfRef;
    }

}
