// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.Sql;

public static partial class GeoBackupPolicyArgsExtensions
{
    public static global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs WithDatabaseName(this global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs @selfRef, global::System.String databaseName)
    {
        @selfRef.DatabaseName = databaseName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs WithGeoBackupPolicyName(this global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs @selfRef, global::System.String geoBackupPolicyName)
    {
        @selfRef.GeoBackupPolicyName = geoBackupPolicyName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs WithResourceGroupName(this global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs WithServerName(this global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs @selfRef, global::System.String serverName)
    {
        @selfRef.ServerName = serverName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs WithState(this global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs @selfRef, global::Pulumi.AzureNative.Sql.GeoBackupPolicyState state)
    {
        @selfRef.State = state;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs WithState(this global::Pulumi.AzureNative.Sql.GeoBackupPolicyArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.Sql.GeoBackupPolicyState> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AzureNative.Sql.GeoBackupPolicyState>();
        @configure(@item);
        @selfRef.State = @item;
        return @selfRef;
    }

}
