// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.Workloads;

public static partial class ACSSBackupConnectionArgsExtensions
{
    public static global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs WithBackupName(this global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs @selfRef, global::System.String backupName)
    {
        @selfRef.BackupName = backupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs WithConnectorName(this global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs @selfRef, global::System.String connectorName)
    {
        @selfRef.ConnectorName = connectorName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs WithLocation(this global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs WithResourceGroupName(this global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs WithTags(this global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs WithTags(this global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs WithTags(this global::Pulumi.AzureNative.Workloads.ACSSBackupConnectionArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
