// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.ImageBuilder;

public static partial class ContainerRecipeArgsExtensions
{
    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithComponents(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeComponentConfigurationArgs> components)
    {
        @selfRef.Components = components;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithComponents(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeComponentConfigurationArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeComponentConfigurationArgs>();
        @configure(@list);
        @selfRef.Components = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithComponents(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeComponentConfigurationArgs>> @create)
    {
        @selfRef.Components = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithContainerType(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeContainerType containerType)
    {
        @selfRef.ContainerType = containerType;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithContainerType(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeContainerType> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeContainerType>();
        @configure(@item);
        @selfRef.ContainerType = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithDescription(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithDockerfileTemplateData(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String dockerfileTemplateData)
    {
        @selfRef.DockerfileTemplateData = dockerfileTemplateData;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithDockerfileTemplateUri(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String dockerfileTemplateUri)
    {
        @selfRef.DockerfileTemplateUri = dockerfileTemplateUri;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithImageOsVersionOverride(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String imageOsVersionOverride)
    {
        @selfRef.ImageOsVersionOverride = imageOsVersionOverride;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithInstanceConfiguration(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeInstanceConfigurationArgs instanceConfiguration)
    {
        @selfRef.InstanceConfiguration = instanceConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithInstanceConfiguration(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeInstanceConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeInstanceConfigurationArgs();
        @configure(@item);
        @selfRef.InstanceConfiguration = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithKmsKeyId(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String kmsKeyId)
    {
        @selfRef.KmsKeyId = kmsKeyId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithName(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithParentImage(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String parentImage)
    {
        @selfRef.ParentImage = parentImage;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithPlatformOverride(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::Pulumi.AwsNative.ImageBuilder.ContainerRecipePlatformOverride platformOverride)
    {
        @selfRef.PlatformOverride = platformOverride;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithPlatformOverride(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.ImageBuilder.ContainerRecipePlatformOverride> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.ImageBuilder.ContainerRecipePlatformOverride>();
        @configure(@item);
        @selfRef.PlatformOverride = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithTags(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithTags(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithTags(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithTargetRepository(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeTargetContainerRepositoryArgs targetRepository)
    {
        @selfRef.TargetRepository = targetRepository;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithTargetRepository(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeTargetContainerRepositoryArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.ImageBuilder.Inputs.ContainerRecipeTargetContainerRepositoryArgs();
        @configure(@item);
        @selfRef.TargetRepository = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithVersion(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String version)
    {
        @selfRef.Version = version;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs WithWorkingDirectory(this global::Pulumi.AwsNative.ImageBuilder.ContainerRecipeArgs @selfRef, global::System.String workingDirectory)
    {
        @selfRef.WorkingDirectory = workingDirectory;
        return @selfRef;
    }

}
