// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.ImageBuilder.Inputs;

namespace Pulumi.AwsNative.ImageBuilder;

public static partial class InfrastructureConfigurationS3LogsArgsExtensions
{
    public static global::Pulumi.AwsNative.ImageBuilder.Inputs.InfrastructureConfigurationS3LogsArgs WithS3BucketName(this global::Pulumi.AwsNative.ImageBuilder.Inputs.InfrastructureConfigurationS3LogsArgs @selfRef, global::System.String s3BucketName)
    {
        @selfRef.S3BucketName = s3BucketName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.ImageBuilder.Inputs.InfrastructureConfigurationS3LogsArgs WithS3KeyPrefix(this global::Pulumi.AwsNative.ImageBuilder.Inputs.InfrastructureConfigurationS3LogsArgs @selfRef, global::System.String s3KeyPrefix)
    {
        @selfRef.S3KeyPrefix = s3KeyPrefix;
        return @selfRef;
    }

}
