// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.ApiManagement.Inputs;

namespace Pulumi.AzureNative.ApiManagement;

public static partial class ApiVersionSetContractDetailsArgsExtensions
{
    public static global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs WithDescription(this global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs WithId(this global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs @selfRef, global::System.String id)
    {
        @selfRef.Id = id;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs WithName(this global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs WithVersionHeaderName(this global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs @selfRef, global::System.String versionHeaderName)
    {
        @selfRef.VersionHeaderName = versionHeaderName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs WithVersionQueryName(this global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs @selfRef, global::System.String versionQueryName)
    {
        @selfRef.VersionQueryName = versionQueryName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs WithVersioningScheme(this global::Pulumi.AzureNative.ApiManagement.Inputs.ApiVersionSetContractDetailsArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.ApiManagement.VersioningScheme> versioningScheme)
    {
        @selfRef.VersioningScheme = versioningScheme;
        return @selfRef;
    }

}
