// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.NimbleStudio;

public static partial class LaunchProfileArgsExtensions
{
    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithDescription(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithEc2SubnetIds(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Collections.Generic.List<global::System.String> ec2SubnetIds)
    {
        @selfRef.Ec2SubnetIds = ec2SubnetIds;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithEc2SubnetIds(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Ec2SubnetIds = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithEc2SubnetIds(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Ec2SubnetIds = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithLaunchProfileProtocolVersions(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Collections.Generic.List<global::System.String> launchProfileProtocolVersions)
    {
        @selfRef.LaunchProfileProtocolVersions = launchProfileProtocolVersions;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithLaunchProfileProtocolVersions(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.LaunchProfileProtocolVersions = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithLaunchProfileProtocolVersions(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.LaunchProfileProtocolVersions = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithName(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithStreamConfiguration(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::Pulumi.AwsNative.NimbleStudio.Inputs.LaunchProfileStreamConfigurationArgs streamConfiguration)
    {
        @selfRef.StreamConfiguration = streamConfiguration;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithStreamConfiguration(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.NimbleStudio.Inputs.LaunchProfileStreamConfigurationArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.NimbleStudio.Inputs.LaunchProfileStreamConfigurationArgs();
        @configure(@item);
        @selfRef.StreamConfiguration = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithStudioComponentIds(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Collections.Generic.List<global::System.String> studioComponentIds)
    {
        @selfRef.StudioComponentIds = studioComponentIds;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithStudioComponentIds(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.StudioComponentIds = @list;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithStudioComponentIds(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.StudioComponentIds = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithStudioId(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.String studioId)
    {
        @selfRef.StudioId = studioId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithTags(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithTags(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs WithTags(this global::Pulumi.AwsNative.NimbleStudio.LaunchProfileArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

}
