// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Network.Inputs;

namespace Pulumi.AzureNative.Network;

public static partial class ApplicationGatewayBackendAddressArgsExtensions
{
    public static global::Pulumi.AzureNative.Network.Inputs.ApplicationGatewayBackendAddressArgs WithFqdn(this global::Pulumi.AzureNative.Network.Inputs.ApplicationGatewayBackendAddressArgs @selfRef, global::System.String fqdn)
    {
        @selfRef.Fqdn = fqdn;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.Inputs.ApplicationGatewayBackendAddressArgs WithIpAddress(this global::Pulumi.AzureNative.Network.Inputs.ApplicationGatewayBackendAddressArgs @selfRef, global::System.String ipAddress)
    {
        @selfRef.IpAddress = ipAddress;
        return @selfRef;
    }

}
