// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Network.Inputs;

namespace Pulumi.AzureNative.Network;

public static partial class FirewallPolicyFilterRuleCollectionActionArgsExtensions
{
    public static global::Pulumi.AzureNative.Network.Inputs.FirewallPolicyFilterRuleCollectionActionArgs WithType(this global::Pulumi.AzureNative.Network.Inputs.FirewallPolicyFilterRuleCollectionActionArgs @selfRef, global::Pulumi.Union<global::System.String, global::Pulumi.AzureNative.Network.FirewallPolicyFilterRuleCollectionActionType> type)
    {
        @selfRef.Type = type;
        return @selfRef;
    }

}
