// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.Network;

public static partial class HubRouteTableArgsExtensions
{
    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithId(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.String id)
    {
        @selfRef.Id = id;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithLabels(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.Collections.Generic.List<global::System.String> labels)
    {
        @selfRef.Labels = labels;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithLabels(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::System.String>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::System.String>();
        @configure(@list);
        @selfRef.Labels = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithLabels(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::System.String>> @create)
    {
        @selfRef.Labels = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithName(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithResourceGroupName(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithRouteTableName(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.String routeTableName)
    {
        @selfRef.RouteTableName = routeTableName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithRoutes(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.Network.Inputs.HubRouteArgs> routes)
    {
        @selfRef.Routes = routes;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithRoutes(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.Network.Inputs.HubRouteArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.Network.Inputs.HubRouteArgs>();
        @configure(@list);
        @selfRef.Routes = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithRoutes(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.Network.Inputs.HubRouteArgs>> @create)
    {
        @selfRef.Routes = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Network.HubRouteTableArgs WithVirtualHubName(this global::Pulumi.AzureNative.Network.HubRouteTableArgs @selfRef, global::System.String virtualHubName)
    {
        @selfRef.VirtualHubName = virtualHubName;
        return @selfRef;
    }

}
