// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AzureArcData.Inputs;

namespace Pulumi.AzureNative.AzureArcData;

public static partial class SqlManagedInstanceSkuArgsExtensions
{
    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithCapacity(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, global::System.Int32 capacity)
    {
        @selfRef.Capacity = capacity;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithDev(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, bool dev = true)
    {
        @selfRef.Dev = dev;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithFamily(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, global::System.String family)
    {
        @selfRef.Family = family;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithName(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, global::Pulumi.AzureNative.AzureArcData.SqlManagedInstanceSkuName name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithName(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AzureArcData.SqlManagedInstanceSkuName> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AzureNative.AzureArcData.SqlManagedInstanceSkuName>();
        @configure(@item);
        @selfRef.Name = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithSize(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, global::System.String size)
    {
        @selfRef.Size = size;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithTier(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, global::Pulumi.AzureNative.AzureArcData.SqlManagedInstanceSkuTier tier)
    {
        @selfRef.Tier = tier;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs WithTier(this global::Pulumi.AzureNative.AzureArcData.Inputs.SqlManagedInstanceSkuArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.AzureArcData.SqlManagedInstanceSkuTier> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AzureNative.AzureArcData.SqlManagedInstanceSkuTier>();
        @configure(@item);
        @selfRef.Tier = @item;
        return @selfRef;
    }

}
