// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.DataSync.Inputs;

namespace Pulumi.AwsNative.DataSync;

public static partial class TaskScheduleArgsExtensions
{
    public static global::Pulumi.AwsNative.DataSync.Inputs.TaskScheduleArgs WithScheduleExpression(this global::Pulumi.AwsNative.DataSync.Inputs.TaskScheduleArgs @selfRef, global::System.String scheduleExpression)
    {
        @selfRef.ScheduleExpression = scheduleExpression;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.DataSync.Inputs.TaskScheduleArgs WithStatus(this global::Pulumi.AwsNative.DataSync.Inputs.TaskScheduleArgs @selfRef, global::Pulumi.AwsNative.DataSync.TaskScheduleStatus status)
    {
        @selfRef.Status = status;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.DataSync.Inputs.TaskScheduleArgs WithStatus(this global::Pulumi.AwsNative.DataSync.Inputs.TaskScheduleArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.DataSync.TaskScheduleStatus> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.DataSync.TaskScheduleStatus>();
        @configure(@item);
        @selfRef.Status = @item;
        return @selfRef;
    }

}
