// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.IvsChat.Inputs;

namespace Pulumi.AwsNative.IvsChat;

public static partial class LoggingConfigurationS3DestinationConfigurationArgsExtensions
{
    public static global::Pulumi.AwsNative.IvsChat.Inputs.LoggingConfigurationS3DestinationConfigurationArgs WithBucketName(this global::Pulumi.AwsNative.IvsChat.Inputs.LoggingConfigurationS3DestinationConfigurationArgs @selfRef, global::System.String bucketName)
    {
        @selfRef.BucketName = bucketName;
        return @selfRef;
    }

}
