// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Dms.Inputs;

namespace Pulumi.AwsNative.Dms;

public static partial class SettingsPropertiesMariaDbSettingsPropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs WithCertificateArn(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs @selfRef, global::System.String certificateArn)
    {
        @selfRef.CertificateArn = certificateArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs WithPort(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs @selfRef, global::System.Int32 port)
    {
        @selfRef.Port = port;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs WithServerName(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs @selfRef, global::System.String serverName)
    {
        @selfRef.ServerName = serverName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs WithSslMode(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs @selfRef, global::Pulumi.AwsNative.Dms.DataProviderDmsSslModeValue sslMode)
    {
        @selfRef.SslMode = sslMode;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs WithSslMode(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMariaDbSettingsPropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Dms.DataProviderDmsSslModeValue> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Dms.DataProviderDmsSslModeValue>();
        @configure(@item);
        @selfRef.SslMode = @item;
        return @selfRef;
    }

}
