// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Dms.Inputs;

namespace Pulumi.AwsNative.Dms;

public static partial class SettingsPropertiesMongoDbSettingsPropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithAuthMechanism(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::Pulumi.AwsNative.Dms.DataProviderMongoDbAuthMechanism authMechanism)
    {
        @selfRef.AuthMechanism = authMechanism;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithAuthMechanism(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Dms.DataProviderMongoDbAuthMechanism> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Dms.DataProviderMongoDbAuthMechanism>();
        @configure(@item);
        @selfRef.AuthMechanism = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithAuthSource(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.String authSource)
    {
        @selfRef.AuthSource = authSource;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithAuthType(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::Pulumi.AwsNative.Dms.DataProviderMongoDbAuthType authType)
    {
        @selfRef.AuthType = authType;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithAuthType(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Dms.DataProviderMongoDbAuthType> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Dms.DataProviderMongoDbAuthType>();
        @configure(@item);
        @selfRef.AuthType = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithCertificateArn(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.String certificateArn)
    {
        @selfRef.CertificateArn = certificateArn;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithDatabaseName(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.String databaseName)
    {
        @selfRef.DatabaseName = databaseName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithPort(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.Int32 port)
    {
        @selfRef.Port = port;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithServerName(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.String serverName)
    {
        @selfRef.ServerName = serverName;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithSslMode(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::Pulumi.AwsNative.Dms.DataProviderMongoDbSslModeValue sslMode)
    {
        @selfRef.SslMode = sslMode;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs WithSslMode(this global::Pulumi.AwsNative.Dms.Inputs.SettingsPropertiesMongoDbSettingsPropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Dms.DataProviderMongoDbSslModeValue> @configure)
    {
        var @item = global::System.Activator.CreateInstance<global::Pulumi.AwsNative.Dms.DataProviderMongoDbSslModeValue>();
        @configure(@item);
        @selfRef.SslMode = @item;
        return @selfRef;
    }

}
