// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.AppPlatform.Inputs;

namespace Pulumi.AzureNative.AppPlatform;

public static partial class ErrorArgsExtensions
{
    public static global::Pulumi.AzureNative.AppPlatform.Inputs.ErrorArgs WithCode(this global::Pulumi.AzureNative.AppPlatform.Inputs.ErrorArgs @selfRef, global::System.String code)
    {
        @selfRef.Code = code;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.AppPlatform.Inputs.ErrorArgs WithMessage(this global::Pulumi.AzureNative.AppPlatform.Inputs.ErrorArgs @selfRef, global::System.String message)
    {
        @selfRef.Message = message;
        return @selfRef;
    }

}
