// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Location;

public static partial class MapExtensions
{

    extension(Map)
    {
        public static Map New(string @id, global::Pulumi.AwsNative.Location.MapArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new Map(@id, @args, @options);
        }

        public static Map New(string @id, global::System.Action<global::Pulumi.AwsNative.Location.MapArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AwsNative.Location.MapArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new Map(@id, @args, @options);
        }

    }

}
