// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.DataBoxEdge;

public static partial class FileEventTriggerArgsExtensions
{
    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithCustomContextTag(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::System.String customContextTag)
    {
        @selfRef.CustomContextTag = customContextTag;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithDeviceName(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::System.String deviceName)
    {
        @selfRef.DeviceName = deviceName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithKind(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::System.String kind)
    {
        @selfRef.Kind = kind;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithName(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::System.String name)
    {
        @selfRef.Name = name;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithResourceGroupName(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithSinkInfo(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::Pulumi.AzureNative.DataBoxEdge.Inputs.RoleSinkInfoArgs sinkInfo)
    {
        @selfRef.SinkInfo = sinkInfo;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithSinkInfo(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DataBoxEdge.Inputs.RoleSinkInfoArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DataBoxEdge.Inputs.RoleSinkInfoArgs();
        @configure(@item);
        @selfRef.SinkInfo = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithSourceInfo(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::Pulumi.AzureNative.DataBoxEdge.Inputs.FileSourceInfoArgs sourceInfo)
    {
        @selfRef.SourceInfo = sourceInfo;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs WithSourceInfo(this global::Pulumi.AzureNative.DataBoxEdge.FileEventTriggerArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.DataBoxEdge.Inputs.FileSourceInfoArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.DataBoxEdge.Inputs.FileSourceInfoArgs();
        @configure(@item);
        @selfRef.SourceInfo = @item;
        return @selfRef;
    }

}
