// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Media.Inputs;

namespace Pulumi.AzureNative.Media;

public static partial class EnabledProtocolsArgsExtensions
{
    public static global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs WithDash(this global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs @selfRef, bool dash = true)
    {
        @selfRef.Dash = dash;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs WithDownload(this global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs @selfRef, bool download = true)
    {
        @selfRef.Download = download;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs WithHls(this global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs @selfRef, bool hls = true)
    {
        @selfRef.Hls = hls;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs WithSmoothStreaming(this global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs @selfRef, bool smoothStreaming = true)
    {
        @selfRef.SmoothStreaming = smoothStreaming;
        return @selfRef;
    }

}
