// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AzureNative.Media.Inputs;

namespace Pulumi.AzureNative.Media;

public static partial class EnvelopeEncryptionArgsExtensions
{
    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithClearTracks(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.Media.Inputs.TrackSelectionArgs> clearTracks)
    {
        @selfRef.ClearTracks = clearTracks;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithClearTracks(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.Media.Inputs.TrackSelectionArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.Media.Inputs.TrackSelectionArgs>();
        @configure(@list);
        @selfRef.ClearTracks = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithClearTracks(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.Media.Inputs.TrackSelectionArgs>> @create)
    {
        @selfRef.ClearTracks = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithContentKeys(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::Pulumi.AzureNative.Media.Inputs.StreamingPolicyContentKeysArgs contentKeys)
    {
        @selfRef.ContentKeys = contentKeys;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithContentKeys(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.Media.Inputs.StreamingPolicyContentKeysArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.Media.Inputs.StreamingPolicyContentKeysArgs();
        @configure(@item);
        @selfRef.ContentKeys = @item;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithCustomKeyAcquisitionUrlTemplate(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::System.String customKeyAcquisitionUrlTemplate)
    {
        @selfRef.CustomKeyAcquisitionUrlTemplate = customKeyAcquisitionUrlTemplate;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithEnabledProtocols(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs enabledProtocols)
    {
        @selfRef.EnabledProtocols = enabledProtocols;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs WithEnabledProtocols(this global::Pulumi.AzureNative.Media.Inputs.EnvelopeEncryptionArgs @selfRef, global::System.Action<global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs> @configure)
    {
        var @item = new global::Pulumi.AzureNative.Media.Inputs.EnabledProtocolsArgs();
        @configure(@item);
        @selfRef.EnabledProtocols = @item;
        return @selfRef;
    }

}
