// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.Orbital;

public static partial class SpacecraftArgsExtensions
{
    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithLinks(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.Collections.Generic.List<global::Pulumi.AzureNative.Orbital.Inputs.SpacecraftLinkArgs> links)
    {
        @selfRef.Links = links;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithLinks(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.Action<global::System.Collections.Generic.List<global::Pulumi.AzureNative.Orbital.Inputs.SpacecraftLinkArgs>> @configure)
    {
        var @list = new global::System.Collections.Generic.List<global::Pulumi.AzureNative.Orbital.Inputs.SpacecraftLinkArgs>();
        @configure(@list);
        @selfRef.Links = @list;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithLinks(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.Func<global::System.Collections.Generic.IEnumerable<global::Pulumi.AzureNative.Orbital.Inputs.SpacecraftLinkArgs>> @create)
    {
        @selfRef.Links = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithLocation(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.String location)
    {
        @selfRef.Location = location;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithNoradId(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.String noradId)
    {
        @selfRef.NoradId = noradId;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithResourceGroupName(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.String resourceGroupName)
    {
        @selfRef.ResourceGroupName = resourceGroupName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithSpacecraftName(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.String spacecraftName)
    {
        @selfRef.SpacecraftName = spacecraftName;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithTags(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.Collections.Generic.Dictionary<string, global::System.String> tags)
    {
        @selfRef.Tags = tags;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithTags(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.Action<global::System.Collections.Generic.Dictionary<string, global::System.String>> @configure)
    {
        var @dict = new global::System.Collections.Generic.Dictionary<string, global::System.String>();
        @configure(@dict);
        @selfRef.Tags = @dict;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithTags(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.Func<global::System.Collections.Generic.IDictionary<string, global::System.String>> @create)
    {
        @selfRef.Tags = global::Pulumi.Output.Create(@create());
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithTitleLine(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.String titleLine)
    {
        @selfRef.TitleLine = titleLine;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithTleLine1(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.String tleLine1)
    {
        @selfRef.TleLine1 = tleLine1;
        return @selfRef;
    }

    public static global::Pulumi.AzureNative.Orbital.SpacecraftArgs WithTleLine2(this global::Pulumi.AzureNative.Orbital.SpacecraftArgs @selfRef, global::System.String tleLine2)
    {
        @selfRef.TleLine2 = tleLine2;
        return @selfRef;
    }

}
