// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.DelegatedNetwork;

public static partial class OrchestratorInstanceServiceDetailsExtensions
{

    extension(OrchestratorInstanceServiceDetails)
    {
        public static OrchestratorInstanceServiceDetails New(string @id, global::Pulumi.AzureNative.DelegatedNetwork.OrchestratorInstanceServiceDetailsArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new OrchestratorInstanceServiceDetails(@id, @args, @options);
        }

        public static OrchestratorInstanceServiceDetails New(string @id, global::System.Action<global::Pulumi.AzureNative.DelegatedNetwork.OrchestratorInstanceServiceDetailsArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AzureNative.DelegatedNetwork.OrchestratorInstanceServiceDetailsArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new OrchestratorInstanceServiceDetails(@id, @args, @options);
        }

    }

}
