// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AzureNative.Authorization;

public static partial class ManagementLockAtResourceGroupLevelExtensions
{

    extension(ManagementLockAtResourceGroupLevel)
    {
        public static ManagementLockAtResourceGroupLevel New(string @id, global::Pulumi.AzureNative.Authorization.ManagementLockAtResourceGroupLevelArgs @args, global::Pulumi.CustomResourceOptions? @options = null)
        {
            return new ManagementLockAtResourceGroupLevel(@id, @args, @options);
        }

        public static ManagementLockAtResourceGroupLevel New(string @id, global::System.Action<global::Pulumi.AzureNative.Authorization.ManagementLockAtResourceGroupLevelArgs>? @configureArgs = null, global::System.Action<global::Pulumi.CustomResourceOptions>? @configureOptions = null)
        {
            global::Pulumi.AzureNative.Authorization.ManagementLockAtResourceGroupLevelArgs @args = new();
            global::Pulumi.CustomResourceOptions? @options = null;
            if (@configureArgs is not null)
            {
                @configureArgs(@args);
            }

            if (@configureOptions is not null)
            {
                @options = new();
                @configureOptions(@options);
            }

            return new ManagementLockAtResourceGroupLevel(@id, @args, @options);
        }

    }

}
