// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.AppFlow.Inputs;

namespace Pulumi.AwsNative.AppFlow;

public static partial class ConnectorProfileInforNexusConnectorProfilePropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.AppFlow.Inputs.ConnectorProfileInforNexusConnectorProfilePropertiesArgs WithInstanceUrl(this global::Pulumi.AwsNative.AppFlow.Inputs.ConnectorProfileInforNexusConnectorProfilePropertiesArgs @selfRef, global::System.String instanceUrl)
    {
        @selfRef.InstanceUrl = instanceUrl;
        return @selfRef;
    }

}
