// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

namespace Pulumi.AwsNative.Connect;

public static partial class ContactFlowVersionArgsExtensions
{
    public static global::Pulumi.AwsNative.Connect.ContactFlowVersionArgs WithContactFlowId(this global::Pulumi.AwsNative.Connect.ContactFlowVersionArgs @selfRef, global::System.String contactFlowId)
    {
        @selfRef.ContactFlowId = contactFlowId;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Connect.ContactFlowVersionArgs WithDescription(this global::Pulumi.AwsNative.Connect.ContactFlowVersionArgs @selfRef, global::System.String description)
    {
        @selfRef.Description = description;
        return @selfRef;
    }

}
