// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.Connect.Inputs;

namespace Pulumi.AwsNative.Connect;

public static partial class EvaluationFormQuestionTypePropertiesArgsExtensions
{
    public static global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs WithNumeric(this global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs @selfRef, global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormNumericQuestionPropertiesArgs numeric)
    {
        @selfRef.Numeric = numeric;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs WithNumeric(this global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormNumericQuestionPropertiesArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormNumericQuestionPropertiesArgs();
        @configure(@item);
        @selfRef.Numeric = @item;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs WithSingleSelect(this global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs @selfRef, global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormSingleSelectQuestionPropertiesArgs singleSelect)
    {
        @selfRef.SingleSelect = singleSelect;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs WithSingleSelect(this global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormQuestionTypePropertiesArgs @selfRef, global::System.Action<global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormSingleSelectQuestionPropertiesArgs> @configure)
    {
        var @item = new global::Pulumi.AwsNative.Connect.Inputs.EvaluationFormSingleSelectQuestionPropertiesArgs();
        @configure(@item);
        @selfRef.SingleSelect = @item;
        return @selfRef;
    }

}
