// <auto-generated/>
// Do not edit any code this file. Create or edit the partial class instead in a different file.

#nullable enable

using Pulumi.AwsNative.IoTEvents.Inputs;

namespace Pulumi.AwsNative.IoTEvents;

public static partial class DetectorModelAssetPropertyVariantArgsExtensions
{
    public static global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs WithBooleanValue(this global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs @selfRef, global::System.String booleanValue)
    {
        @selfRef.BooleanValue = booleanValue;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs WithDoubleValue(this global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs @selfRef, global::System.String doubleValue)
    {
        @selfRef.DoubleValue = doubleValue;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs WithIntegerValue(this global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs @selfRef, global::System.String integerValue)
    {
        @selfRef.IntegerValue = integerValue;
        return @selfRef;
    }

    public static global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs WithStringValue(this global::Pulumi.AwsNative.IoTEvents.Inputs.DetectorModelAssetPropertyVariantArgs @selfRef, global::System.String stringValue)
    {
        @selfRef.StringValue = stringValue;
        return @selfRef;
    }

}
